### ISSUE TITLE
Pro Bowl game is not being listed

### ISSUE THREAD

**Issue by dahlSTROM** [Alexqw/xbmc-gamepass#154] opened 2015-01-21 13:54 UTC
The Pro Bowl games are not showing for the 2014 or 2013 season. My guess is that it has something to do with the team names being empty but I unfortunately don't have the time to debug it.

Here's the response from http://gamepass.nfl.com/nflgp/servlets/games:
```
<?xml version="1.0" encoding="UTF-8"?>
<result>
	<season>2014</season>
	<week>221</week>
	
	
	<currentDate>2015-01-21T08:40:46.946</currentDate>
	<games>
		
			<game>
				<id>56501</id>
				
				<season>2014</season>
				<week>21</week>
				<type>3</type>
				<date>2015-01-25T20:00:00.000</date>
				<gameTimeGMT>2015-01-26T01:00:00.000</gameTimeGMT>
				
				
				<homeTeam>
					<id>CRT</id>
					<city>Team Carter</city>
					<name></name>
					<score></score>
				</homeTeam>
				<awayTeam>
					<id>IRV</id>
					<city>Team Irvin</city>
					<name></name>
					<score></score>
				</awayTeam>
				
					<elias>2015012500</elias>
				
				
				
				
				
				
					<programId>13661</programId>
				
				
				
				
				
				
			</game>
		
	</games>
	
		<subscription>SEASON_PLUS</subscription>
	
</result>
```

**Comment by kaileu** [comment] 2015-01-21 15:28
The Problem is that the Name Field is blank if you enter something there it would work.

**Comment by Alexqw** [comment] 2015-01-23 12:32
Fixed by @kaileu and in the 0.7.1 release.

**Closed by Alexqw** 2015-01-23 12:32 UTC

**Comment by Alexqw** [comment] 2015-01-23 12:41
Submitted to kodi devs, so it should be in the kodi repo and out to users before the Pro Bowl happens.

---Alex

**Comment by Alexqw** [comment] 2015-01-23 12:59
And liek that, it's already accepted and in the kodi repo. :-)
