### ISSUE TITLE
GamePass on Win 8.1 not working

### ISSUE THREAD

**Issue by pklongball** [Alexqw/xbmc-gamepass#190] opened 2015-08-22 08:11 UTC
Hello, Newbie here so forgive me if I post in the wrong place. But here goes anyway.

I have XBMC/Kodi on a Win 8.1 PC. I started with Gotham and updated to Helix and now Isengard. 
Loading GamePass addon in to Gotham and carried over to Helix and worked well using I believe GamePass v. 0.6 

I have now updated to Kodi 15.1 and GP v 0.7.4 and all I get is the main menu of games and such. If I choose a game to watch the "working" symbol comes on and then after a minute or so I get a pop out that says somebad juju happened please enable debugging.
I have been reading everywhere I can to see what I can do but nothing helps so far.

If I can ask what should I do next?
 I can say that I did get a game to start once or twice but after playing for a minute or so it started to buffer every 10 or 20 seconds and then finally stop and returns to main game window. I don't think this is a network issue as I can switch to my Chrome browser , log in to GamePass and it plays perfectly. Switch back to Kodi and same issue again.

I am located in Thailand on a fiber to home connection and all my internet activiity seems normal except for this.

Thanks for any responses

**Comment by Alexqw** [comment] 2015-08-22 09:05
@pklongball Are you using Game Pass from git or from the Kodi repo? There's a recent bug fix in master that might fix this problem.

Otherwise, you'll need to enable debugging and provide a [debug log](http://kodi.wiki/view/Log_file) for us to be able to provide any help.

---Alex

**Comment by pklongball** [comment] 2015-08-22 09:09
Hello Alex,

Thanks for the quick reply

I loaded the addons from Git Hub since the first one was not in XBMC and
just the other day I downloaded the v 74 from GIT also.

If need I can figure out how to get a report for you

Thanks

PK

**Comment by Alexqw** [comment] 2015-08-22 09:28
@pklongball Damn. I was hoping this would be an easy fix. ;-)

So, definitely we'll need the debug logs. Enable debugging in the Game Pass addon and for Kodi. Follow the instructions in the link above for specifics.

---Alex

**Comment by pklongball** [comment] 2015-08-22 09:35
Alex, sorry but here's the first dumb ass newbie question? What link above for specifics. The debug enabling I can handle and possibly getting a copy of the log to attach here but I see no link. Anyway I will get to it and give it a whirl

PK

**Comment by Alexqw** [comment] 2015-08-22 09:42
Haha. No worries. The "link above" was referring to an earlier comment in this exchange, where I had provided a link to Kodi's instructions for providing a debug log.

> ... you'll need to enable debugging and provide a [debug log](http://kodi.wiki/view/Log_file) for us to be able to provide any help.

---Alex

**Comment by pklongball** [comment] 2015-08-22 10:11
I tried to attach file to GIT but that type of file is not allowed so here
it is in an email

PK

**Comment by Alexqw** [comment] 2015-08-22 10:16
http://pastebin.com/ is a classic option.

**Comment by Alexqw** [comment] 2015-08-22 10:38
@pklongball I did not receive an email. Please use http://pastebin.com/ (or some other service) instead.

---Alx

**Comment by pklongball** [comment] 2015-08-22 11:27
Alex, Sorry cannot send file tonight anymore. I will do in the AM for me here in Thailand. Stay tuned

PK

**Comment by pklongball** [comment] 2015-08-22 14:39
Alex here is a link to the log file on my Dropbox site.

https://www.dropbox.com/s/jtfk1sfxi8iw1si/PK_kodi.log?dl=0

I hope you can see this one

PK

**Comment by Alexqw** [comment] 2015-08-22 17:09
Hmm. Looks like it's having trouble with the HLS stream itself...

This might be a different manifestation of #191 

---Alex

**Comment by pklongball** [comment] 2015-08-23 00:07
Good to know you got the file and happy to hear you see something that is an issue. My untrained eye sees lines of info but that's it. Let me know if I can send any more info or try something specific.

Thanks

PK

**Comment by kaileu** [comment] 2015-08-23 00:19
Did you try a stable Kodi release?
You are using Kodi 16 alpha please try Kodi 15.1 and test it again.

Mit freundlichen Grüßen
KaiLeu

**Comment by pklongball** [comment] 2015-08-23 00:23
Hello,

Actually yes I was on the stable release when I discovered the
problem/issue and thought maybe it was the fault so I decided to try the
newer version with basically the same results.

Maybe today I should downgrade to an earlier version? But not sure what is
comaptible to the GamePasss 74

PK

**Comment by kaileu** [comment] 2015-08-23 00:41
Kodi 15.1 is fine.
The question was only to exclude the possibility that the new version breaks something ;-)

Mit freundlichen Grüßen
Kai Leutner

> Am 23.08.2015 um 02:23 schrieb pklongball <notifications@github.com>:
> 
> Hello,
> 
> Actually yes I was on the stable release when I discovered the
> problem/issue and thought maybe it was the fault so I decided to try the
> newer version with basically the same results.
> 
> Maybe today I should downgrade to an earlier version? But not sure what is
> comaptible to the GamePasss 74
> 
> PK
>

**Comment by BaumSchorle** [comment] 2015-08-23 11:24
@pklongball can you please download the latest master and test again?

**Comment by Alexqw** [comment] 2015-08-23 14:05
@kaileu Highly unlikely that the fix will break anything. Those headers merely declare that our client /supports/ gzip and deflate. As long as our client can handle those responses (which Requests/urllib can), then it won't break anything. The decompression is all handled transparently, and the rest of the code is none-the-wiser. :-)

---Alex

**Comment by kaileu** [comment] 2015-08-23 14:10
@Alexqw no i meant that because he is using Kodi 16 maybe Kodi 16 could change the handling of m3u8.
So i mean with "new" Version Kodi16 not my fix 😁
My english isn't the best one 😂

**Comment by Alexqw** [comment] 2015-08-23 14:14
@kaileu Ahh, my bad. I wasn't reading closely enough. :-)

Kodi 16 will break stuff with the addon -- eventually. I read that they're planning on a new cycle of only breaking skin/addon APIs once every two releases. So Kodi 16 will break compatibility, 17 won't, 18 will, etc.

That being said, I don't think there's too many things that have been merged in 16 that'd affect our addon, yet.

---Alex

**Comment by Craigie52** [comment] 2015-08-24 18:03
Just to add to this I have Kodi 15.1 -ARM 86 running GP v 0.7.4 from an amazon firestick displaying a very similar issue. It will not load any FULL game stream since the this weeks weekend games. The Thursday nights games work fine, anything after that just sits on the working prompt for a bit and then stops. No error is displayed. Condensed game streams work fine for ALL games. FULL game streams work for all the previous weeks games. 

I have a friend with an identical setup having the same issue. Maybe something in the way these FULL game streams are being packaged all of a sudden?

**Comment by kaileu** [comment] 2015-08-24 18:07
Did you use the version of Kodi repository or the git version?

Mit freundlichen Grüßen
Kai Leutner

**Comment by Craigie52** [comment] 2015-08-24 18:11
The Kodi repository, I will give the github version a go and let you know how I get on.

**Comment by Craigie52** [comment] 2015-08-24 18:30
Yep the current github version works as advertised, thanks Kai :)

**Comment by hdn8** [comment] 2015-08-24 21:53
Having same issue, do you mean you compiled from the github source?  >  i.e. osx https://github.com/xbmc/xbmc/blob/master/docs/README.osx

Or is there a builds repo apart from http://kodi.tv/download/ ?

**Comment by Craigie52** [comment] 2015-08-24 22:01
I downloaded the zip from this page, copied it across to the firestick and then used the install from zip option in kodi to install the add-on.

**Comment by mottchew** [comment] 2015-08-24 22:05
i downloaded it from the zip on to Kodi on my PC. Preseason games still not working

**Comment by hdn8** [comment] 2015-08-24 22:05
Oh ok I get it now, thought you guys were talking about the kodi version.  Yep that fixed it!

**Comment by mottchew** [comment] 2015-08-24 22:28
i uninstalled and reinstalled. Works for me on Kodi. Thank you

**Comment by pklongball** [comment] 2015-08-25 00:26
I am still not working but no time right now to copy a log file. I will do some more testing later today.

**Comment by pklongball** [comment] 2015-08-28 10:19
I thought I will make an update here on this issue. I have now done two things that will affect this issue reported. I have updated this HTPC running Win 8.1 to the new Win 10. The upgrade went just fine and so far so good. I also downgraded the Kodi 16 beta version back to the stable 15.1 Isengard.

I have done some very limited tries using GP with this new setup but as I see it I still have the same issue. The GP opens to the main menu of games and when I click a game I may get lucky and the game starts and plays for anywhere from a few seconds to a minute but then the screen kicks back to the menu of games or if the game never starts the Error screen shows up. 

Next chance I get I will try to send another log file.

Hope someone has a working Kodi GP addon. At least I have my browser to fall back on as it works just fine

**Comment by Alexqw** [comment] 2015-08-28 10:42
> Hope someone has a working Kodi GP addon. At least I have my browser to fall back on as it works just fine

Umm. It's working for pretty much all of us. The issue is with your setup. We're happy to help troubleshoot, but don't conflate that with the addon being broken.

You neglected to mention if you're running the latest addon code from master.

I look forward to seeing the log.

---Alex

**Comment by pklongball** [comment] 2015-08-28 10:51
Hello,

I am not condemning the add on as broken. Only stating I get 2 different
results from Kodi to browser use of GP.

You mention my setup may be at fault. I would welcome the troubleshooting
of my system to tell me what is going on. Can the log files tell you where
in my setup I have an issue if I do. I am certainly not qualified to point
fingers it just befuddles me to see GP working more or less perfect on my
Chrome but not work from Kodi.

When I say the system is not working this is for replays only at this
point. I have not been home to play live pre season games as yet due to
time differences and sleep times here in Thailand. I will endeavor to
locate someone else here in Thailand with Kodi and the addon so I can see
what experiences they have.

Thanks for any and all help and suggestions

PK

**Comment by hdn8** [comment] 2015-08-28 11:05
I suspect the issue is that you are using the GP plugin from the kodi repo
and not from github. You should uninstall the plugin and reinstall it 'from
a zip file':
Go to https://github.com/Alexqw/xbmc-gamepass, and find the option
"Download ZIP" on the right, uninstall the plugin in kodi and then "install
from zip" using the file you downloaded.

**Comment by pklongball** [comment] 2015-08-28 11:10
yes this is exactly what I have done late last week. Before downloading the master file i went in to the Kodi add on folder and  deleted any files that had a GP name. As I recall there were 2 or 3 files from the past in there also.

PK

**Comment by Alexqw** [comment] 2015-08-28 11:41
@pklongball Please follow @hdn8's instructions. Fixes have gone into master since "late last week."

And then, if you have problems. Be sure to provide a log file. Otherwise it's all just guessing.

---Alex

**Comment by pklongball** [comment] 2015-08-29 08:05
Here is a dropbox link to a log file showing the latest GP 0.8.0 Master add on running in Kodi 15.1 and Win 10 PC

https://www.dropbox.com/s/ucwzg9mqurq65kd/20150829_kodi.log?dl=0

I have no luck running this either. I hope you can pin point something you see in this file that I can correct.

Thanks

PK

**Comment by Alexqw** [comment] 2015-08-29 09:00
I wonder if it has anything to do with this line:

    09:07:37 T:3364   ERROR: CCurlFile::GetCookies - invalid cookie: '.neulion.com	TRUE	/	FALSE	0	nlqpti	'

The stream subsequently times out and fails to play.

It seems to fail with all cookies (tvdb, google, etc).

---Alex

**Comment by kaileu** [comment] 2015-08-29 09:08
This happens oft but no real issue but there are a few duplicated packages and timeouts i think its more a network Problem. 
Maybe its worth to test a lower bitrate. Kodis implementation of hls isn't the best one and struggles with Network Problems.

Mit freundlichen Grüßen
KaiLeu

**Comment by pklongball** [comment] 2015-08-29 09:17
I have tried to drop the viewer bit rate down to as low as it can go and I still get connection or keep running issues. Not sure what I can do next. As I mentioned when I use the NFL browser connection it seems to run fine and the net quality seems to stay above 1200 to as high as it can go when using the use the highest bit rate as possible setting. The Kodi addon only has set choices and I have tried different ones with no real luck there.
Maybe if there is a stability issue with my internet connection and the quality of the signal drops for a few seconds the Kodi system can't handle this change? I am grasping here as I am way out of my area of expertise

Thanks

PK

**Comment by kaileu** [comment] 2015-08-29 09:33
Kodi download only the parts you want to look at the current time not more (no buffering). The apps/browser will buffer the streams wich means it downloads more then you currently needed. If you pause the download will continue in the background. But Kodi didn't has these features. Maybe one of the other devs see something i didn't but don't know....
Maybe you could post a new logfile:
Start Kodi go under settings system debug component specific debug and turn on the components libcurl ffmpeg and video. Close Kodi delete kodi.log start kodi test a stream close kodi and post the log again. This is needed to verify the cookies and the curl messages but i think its realy a connection Issue.


Mit freundlichen Grüßen
Kai Leutner

**Comment by Alexqw** [comment] 2015-08-29 09:34
@pklongball Do you have another box to test on that runs an OS other than WIndows 8/10? That would definitely help narrow down whether this is a Thailand issue or an OS/Kodi issue. Currently, I am leaning towards an OS/Kodi issue, as the Kodi devs have mentioned there's been some problems on Windows 10.

---Alex

**Comment by kaileu** [comment] 2015-08-29 09:58
@Alexqw I am using windows 10 without any problems ;-)

Mit freundlichen Grüßen
KaiLeu

**Comment by pklongball** [comment] 2015-08-29 10:47
Heh, Actually yes I do have my main desktop PC a HP that runs Win 7. I can install Kodi there and give it a try. Dah! Never dawned on me that I could have done that 2 weeks ago Will give that a go maybe later tonight and see what happens

Thanks for the kick start of something to try

PK

**Comment by Alexqw** [comment] 2015-08-29 10:55
@kaileu Ahh, good to know. Which version of kodi?

@pklongball Excellent. I look forward to hearing how it works out.

---Alex

**Comment by pklongball** [comment] 2015-08-29 11:00
Kodi 15.1

**Comment by pklongball** [comment] 2015-08-29 11:23
Update. I just installed Isengard 15.1 and the Master 080 GamePass on my HP. So far the Kodi and the GP are working. I did no configuration stuff to Kodi except turning off the RSS feeds. Fresh install of both Kodi and the add-on. I will continue playing with this setup but in more than 10 minutes of use no hiccups or burps

I think what may be in order now on the MSI HTPC is to completely uninstall Kodi and clear any files that may be corrupt and try a fresh install again. Not  big deal as I only use Kodi for watching downloaded TV and movies and GP. I do not use any live streaming from around the world except for the NFL

**Comment by kaileu** [comment] 2015-08-29 11:31
@alexqw Kodi 15.1

Mit freundlichen Grüßen
KaiLeu

**Comment by pklongball** [comment] 2015-08-29 12:47
Maybe I spoke too soon. Just came back and tried to play again and having difficulty from the HP system. I wonder if this is some network issue now as it played the first time last hour for almost 40 minutes with no stops

**Comment by Alexqw** [comment] 2015-09-10 08:44
@pklongball Any update on this?

**Comment by pklongball** [comment] 2015-09-10 08:55
Hey thanks for the follow up on my status. I just happen to be checking my emails.

The only update I can give you is nothing has changed since my last comments. I thought maybe my desktop was a resolution but it started to do the same thing. So I stopped trying that machine and went back to the original HTPC with Win 10 and tried several variations of things and got no where. The games will start sometimes and play as I said from the start but most of the time I get maybe 1 minute before it either buffers too much and then reverts back to the game menu or the games never start and I get the big error message.

I don't know what else to do at this point and I have resigned myself to watch on the web browser as this always works for me.

Alex if you have any more suggestions I will give it a go over the next days.

This is very frustrating as I cannot pin down what is different now as compared to last season up to the Superbowl as all was perfect then. I wish I could get that same setup as I am not sure what version Kodi and addon I used then so no hope there.

Thanks

PK

**Comment by Alexqw** [comment] 2015-09-10 09:04
@pklongball This is very odd, as you seem to be the only one experiencing this problem (as far as I am aware). @kaileu is using Windows 10 successfully, so it's not a platform issue, and you're both using Kodi 15+.
It's possible it's a geographic thing and Game Pass's servers behave differently near Thailand, but that seems unlikely and is a stretch.
For those who are following along: does anyone know any users in South East Asia (with or without success)?

@pklongball I don't know what else you have installed on that machine, but have you considered a clean-wipe? Reinstall with just Windows, install only kodi 15.2, and then install the addon. It /should/ work. Another option, would be to install Kodibuntu in a virtual machine (just for testing) and test if that works. That'll help narrow down whether it's a geographic problem or an OS problem.

Let me know what you think.

---Alex

**Comment by pklongball** [comment] 2015-09-10 09:10
I will consider some of these thoughts. I will also start a thread on the local Thailand forum and see if anyone is using Kodi with the GP addon. I am aware of several folks on GP and never hear anything one way or another. We are infamous for having weird internet issues so it's possible something with my local ISp fiber service is not right but as I have said a few times the Chrome browser web access works just fine using Win 10 or Win 7.

Thanks I will keep this open for now I guess

**Comment by pklongball** [comment] 2015-09-10 09:12
Oh one more thing is I may take my HTPC to another home and different internet provider and try there

**Comment by Alexqw** [comment] 2015-09-10 09:17
Cool. Let me know how it works out.

**Comment by Alexqw** [comment] 2015-09-22 07:00
@pklongball ping?

---Alex

**Comment by pklongball** [comment] 2015-09-25 13:04
Hey Alex, I see you pinged me and I have waited a few days to gather my thoughts and what I can say.

Bottom line is GP on Kodi with the 0.8.0 master add on is now working for me. 

I had not used the add on for a week or so until this past weekend for week 2 games. I figured I would try it again and much to my surprise the player now is working with some minor/major issues. I can only get the GP to play continuously by leaving the bit rate set to "ask" when starting and then choosing a rate that is in the 3,000 to 1,600 range. I cannot use the 4.5 rate at all.

This is a dramatic improvement from when I opened this issue and could not play anything at any bit rate. With some testing of different rates I can get the GP to play about 99%.
My feeling is that my ISP had some issue with their stability of the line to me and it manifested itself in my experiencing issues with GP and only GP as I do not use Kodi for any online streams except NFL. My browsing and other internet services did not seem to be affected to a degree that I noticed any problems. As stated before my Game Pass player used in Chrome was almost flawless although I did notice the quality would drop to the lowest bit rate from time to time but the video/audio was always there. I see there is only a pick a rate setting or always use the highest rate in the add on. I guess you cannot use the same type of adjust rate on the fly mode that the NFL player has. It would be a nice convenience to have a way to change the rate while playing the games as stopping the game clicking out to the settings and then restarting again is a  tedious way to adjust the rate when the ISP service is spotty. I guess we can't have everything though.

I did go to a local friends place and his subscription to GP is now active on his Linux driven box with XBMC and the add on works great on his line. He has a different ISP than me

Feel free to comment on any of my thoughts and if you want you can close this issue as I don't think you can do any more here.

Thanks

PK

**Comment by kaileu** [comment] 2015-09-25 13:20
Hey,
@pklongball i am not Alex but i can answer one question.
You mentioned the on the fly mode you mentioned is a feature called adaptive bitrate this is a feature that provide the hls format apple uses. The sad thing is Kodi didn't implement this feature and nor did they implement the hls buffering.
These are features i am waiting for but the kodi team has to implement this. Even if we would implement a method to change the bitrate on the fly while watching it would mean the current stream stopps and a new one will be downloaded. And with a bad connection it would not help.


Mit freundlichen Grüßen
KaiLeu

**Comment by Alexqw** [comment] 2015-09-25 13:22
@pklongball Thanks for the update! I'll close this issue then.

About the auto-bandwidth-throttling, it's something that would have to be implemented at the ffmpeg level. There's a feature-request somewhere in their tracker, but I can't find it at the moment. Anyway, if/when ffmpeg supports it, and Kodi includes that version of ffmpeg, then we'll definitely support that option. Caching would help alleviate these problems as well, but that's a Kodi-decision. Hopefully that will change at some point.

Thanks again!

---Alex

**Comment by Alexqw** [comment] 2015-09-25 13:23
@kaileu You beat me to the punch. ;-)

**Closed by Alexqw** 2015-09-25 13:22 UTC
Labels: bug
