### ISSUE TITLE
After a few minutes, streams freeze and crashes back to the main menu of Gamepass

### ISSUE THREAD

**Issue by Displayel** [Alexqw/xbmc-gamepass#187] opened 2015-08-17 12:36 UTC
Hi guys, 

so since version 0.72 and now 0.74 i have this problem that after a few minutes the picture just freezes and crashes back to the Game Pass Main Menu, this is on a FireTV, i never had this kind of issue with Version 0.71.

Here is the log, if there is anything to see :

http://xbmclogs.com/pu3g8stgk

**Comment by Alexqw** [comment] 2015-08-17 12:48
@Displayel This kind of problem can be caused by any of a number of things. First off, can you test with 0.7.1? If that works, then re-upgrade to 0.7.4 and confirm that it's still a problem. We need to make sure both Game Pass and your ISP aren't being a problem.

The stream playing process is part of Kodi and not something this addon has much control over, so it's less likely (though still possible) to be broken by a change we made.

---Alex

**Comment by Alexqw** [comment] 2015-08-17 12:50
Thinking over it more, this is almost certainly a buffering issue. If you press enter (at leats on most skins) during the "freezing" you should see the buffering menu. The "crashing" is Kodi determining it's taking too long to buffer and just exiting the stream. If the entire addon crashed, then that'd be an addon issue, but since it stays in the addon, this really smell like buffering.

What if you just use a lower bitrate?

---Alex

**Comment by Displayel** [comment] 2015-08-17 12:57
Hi, 
yes 0.71 works without any problems, after updating to 0.74 it freezed after a few minutes and went back the main menu, i tried it 2 more times, still the same, then i just downgraded back to 0.71 and its running for like 15 minutes now without any problems

**Comment by Alexqw** [comment] 2015-08-17 13:00
@Displayel That is really weird. Are you watching shows or games?

**Comment by Displayel** [comment] 2015-08-17 13:01
no shows, just NFL Network Live or the Live Games, on last Thursday i watched the Dolphins @ Bears game and for the first time ever there was no buffering at all

**Comment by Alexqw** [comment] 2015-08-17 13:04
Ok, well, only one change went into the 0.7.2 release that affects streams for games. Can you edit `resources/lib/pigskin.py` and change 

    m3u8_header = {'Cookie': 'nlqptid=' + m3u8_param, 'Accept-encoding': 'identity', 'Connection': 'keep-alive'}
to

    m3u8_header = {'Cookie': 'nlqptid=' + temp_parm, 'User-Agent': 'Safari/537.36 Mozilla/5.0 AppleWebKit/537.36 Chrome/31.0.1650.57', 'Accept-encoding': 'identity', 'Connection': 'keep-alive'}

**Comment by dahlSTROM** [comment] 2015-08-17 13:04
I think this is because of 8f3d304d422612e84ed214377a484b8dd61e1489. 
```
ffmpeg[681E9A30]: Unable to open key file http://nlsk.neulion.com/nlsk1/hls/securekey?id=21&url=/nlds/nfl/nfltv/as/live/nfltv_hd_3000/20150817123000.m3u8.key
```

It's the same problem we had before.

**Comment by Alexqw** [comment] 2015-08-17 13:07
@dahlSTROM I didn't see that in the logs. Nice eyes. :-)

I agree, that's the patch I'm looking at as well.

I /really/ hate lying with user agents, but it is what it is. :-/

---Alex

**Comment by Displayel** [comment] 2015-08-17 13:08
Sorry guys, this is all chinese to me, so is it a Kodi Issue or might there be something that i can try ?

**Comment by Alexqw** [comment] 2015-08-17 13:12
@Displayel Are you comfortable editing one line of code? If so, please read my previous comment where I ask you to edit `resources/lib/pigskin.py`

It's likely in ~/.kodi/addons/plugin.video.nfl.gamepass/resources/lib/pigskin.py

**Comment by Displayel** [comment] 2015-08-17 13:16
Hi,
well i don´t have access of the Kodi files on FireTV, its not rooted because the firmware is to new and doesn´t allow it, when i look for your line in the pigskin.py in the addon directly with wordpad, its not finding it :(

**Comment by Alexqw** [comment] 2015-08-17 13:18
Thanks ok. I'll just make the change, since I'm pretty sure that line (aka my patch ;-) is at fault.

I'll let you know when you should retest.

---Alex

**Comment by Displayel** [comment] 2015-08-17 13:24
Hi again, so i did find that line, marked it and replaced it with your new line, does it matter that the layout looks messed up after the past part, although i just marked your original line, but anyways i don´t know if this is the correct way but i then dowloaded the new master again, deleted the original pigskin.py and replaced it with the one with the new line, loaded the new addon in kodi and now when i enter the addon and click on NFL Network Live i get the "Some bad jujumagumbo just went down" so i don´t know if i messed something up  :(

**Comment by Alexqw** [comment] 2015-08-17 13:28
@Displayel Bah. That's my fault. I screwed up somethign in that one-liner. Anyway, I've pushed the fix. Please download the laster master and try.

---Alex

**Comment by Displayel** [comment] 2015-08-17 13:51
So its running for 15 minutes now with no problems so far, looks like you fixed it :)

**Comment by Alexqw** [comment] 2015-08-17 14:04
/Excellent/. Thanks for taking the time to report the bug.

Closing. :-D

---Alex

**Closed by Alexqw** 2015-08-17 14:04 UTC

**Comment by mic4rd** [comment] 2015-08-26 19:25
Sorry for being a complete idiot, but how do I install that "master" with this fix to kodi?

**Comment by Alexqw** [comment] 2015-08-26 19:27
You can either wait a few days for the next release to come out, or you can go to the main page of the repo and click on "Download Zip" on the right side. Then install using that.

---Alex
