### ISSUE TITLE
Streams Dropping....

### ISSUE THREAD

**Issue by v3crax** [Alexqw/xbmc-gamepass#196] opened 2015-08-25 18:26 UTC
Hello, 

I'm using Kodi 14.2 and I'm on version .74 and I'm noticing that my streams have been dropping after around 30 minutes. Not sure if anybody else is having this problem. This happening on both my Windows 7 box and 14.2 Open ELEC Raspberry Pi2 box.

Thanks and Take care

**Comment by Alexqw** [comment] 2015-08-26 07:15
@v3crax Are you running the code from latest master or from the kodi addon repository? This sounds like a bug that has already been fixed in master.

---Alex

**Comment by v3crax** [comment] 2015-08-26 16:56
I originally installed version .60 from github, then that version
automatically updated, I would assume it automatically updated from the
Kodi addon repository.

**Comment by kaileu** [comment] 2015-08-26 17:01
Then you have to wait till the new version will be released in the kodi repo or install the new version from git.

Mit freundlichen Grüßen
KaiLeu

**Comment by v3crax** [comment] 2015-08-26 17:05
Okay, I will remove the add-on and reinstall from Github. Thanks.

**Comment by Alexqw** [comment] 2015-08-26 19:30
Closing, duplicate of #187

**Closed by Alexqw** 2015-08-26 19:30 UTC
Labels: duplicate
