### ISSUE TITLE
NFL Network stream stopping after a few minutes

### ISSUE THREAD

**Issue by mic4rd** [Alexqw/xbmc-gamepass#199] opened 2015-08-26 16:31 UTC
I recently started using Kodi, first on a Win 7 Laptop and now on a fire TV box. The gamepass plugin was the main reason I started using Kodi, because I hated the Flash-based webinterface of Gamepass.

With 0.7.4 I realized that the NFL Network stream is stopping after a few mins, taking me back to the main menu of the Gamepass app. This happens on Kodi 14.2 on the fTV and 15.1 on the laptop. I do not have proxies or anything set.

Streaming of the games works just fine. Is this problem known to anyone, is there a fix?

Thanks in advance!

**Comment by dahlSTROM** [comment] 2015-08-26 16:38
See #187.

**Comment by Alexqw** [comment] 2015-08-26 19:30
@mic4rd Closing, as this is a duplicate of #187 and it's already been fixed.

You can either wait a few days for a new release to hit the Kodi repos, or go to the main page of this repo and click "Download zip" on the right side. Then install using that.

---Alex

**Closed by Alexqw** 2015-08-26 19:30 UTC
