### ISSUE TITLE
Cannot Start neither debug on Kodi 14.2 Openelec Rasp Pi2

### ISSUE THREAD

**Issue by victormr1** [Alexqw/xbmc-gamepass#164] opened 2015-06-26 13:46 UTC
i have been using in the past the add-on without issues but i just got a Raspberry Pi2 with Openelec and works great but when i try to run the add-on i get an error but i have the debug option turned on on the settings and i still get no debug on the program, hope some body can help me

**Comment by BaumSchorle** [comment] 2015-07-03 13:05
Sorry for the late reply, but without any more information, we can not help you.

You at least need to post the log.

**Comment by Alexqw** [comment] 2015-08-10 09:10
@victormr1 I am not able to reproduce your problem with the latest code. I'm going to close this issue now, but if you still have problems, please feel free to reopen and provide a debug log.

---Alex

**Closed by Alexqw** 2015-08-10 09:10 UTC
