### ISSUE TITLE
Pre week 2 games will not play.

### ISSUE THREAD

**Issue by rslynn46** [Alexqw/xbmc-gamepass#195] opened 2015-08-23 22:31 UTC
Pre week 1 games all play fine?

**Comment by kaileu** [comment] 2015-08-24 04:29
With the latest fix from git all games should work.
Stock version from repo some won't.
Alexqw will push a new version at the end of the week.

Mit freundlichen Grüßen
KaiLeu

**Comment by Alexqw** [comment] 2015-08-24 06:48
@rslynn46 The fix for this bug just went in yesterday. You can get the latest code by clicking "Download ZIP" on the right side of the main page of the repo. Or you can use git directly.

Otherwise, as kaileu mentioned,  you'll need to wait until the end of the week for the updated version to hit kodi's servers.

Closing, as it's a duplicate of #191 

---Alex

**Closed by Alexqw** 2015-08-24 06:48 UTC
Labels: duplicate
