### ISSUE TITLE
Hi the-game-will-start-soon video

### ISSUE THREAD

**Issue by SniperQ** [Alexqw/xbmc-gamepass#179] opened 2015-08-14 00:40 UTC
Hi Please How to Show  the Soon the-game-will-start-soon video in repo please thnx

http://www.70-130.com/images/uploads/the-game-will-start-soon-screen-from-nfl-game-pass.jpg

**Comment by BaumSchorle** [comment] 2015-08-14 04:27
I don't know what exactly the problem is, but I can say as soon as a game is marked as 'started' you can stream the video.
The games usually gets marked as started when the broadcast starts, which is about 5 minutes before game starts.

**Comment by chovy** [comment] 2015-08-14 07:19
@SniperQ that "Staring soon" screen is actually the feed. It shows up about 5 minutes before game time when the stream starts. It has nothing to do with this addon.

**Comment by Alexqw** [comment] 2015-08-14 07:22
@BaumSchorle @chovy I agree, that message is entirely in-stream. The only thing we could really improve here is outlined in #119.

Closing. @SniperQ Please feel free to reopen (and explain further) if you feel we have misunderstood your bug report.

---Alex

**Closed by Alexqw** 2015-08-14 07:22 UTC
