### ISSUE TITLE
Some bad jujumajumbo just went down

### ISSUE THREAD

**Issue by 3sons** [Alexqw/xbmc-gamepass#219] opened 2015-11-06 05:26 UTC
Hi,
I just installed this app and seems watching live game or network does not work.  Watching past games seems fine. Here is my log. I hope I did it right, first time.  Hope there is a easy solution/explanation in  this error.  

http://xbmclogs.com/ptepnilpt

Thanks

**Comment by BaumSchorle** [comment] 2015-11-06 05:35
Looks like you are located in Canada and there are some games blacked out. At least the live game you wanted to watch is blacked out on GamePass.

**Comment by BaumSchorle** [comment] 2015-11-06 05:46
This is the same issue as #207

**Comment by Alexqw** [comment] 2015-11-17 09:41
I agree with @BaumSchorle, this is likely a duplicate of #207 
The NFL changed their blackout handling entirely with the merging of Rewind and GamePass. It shouldn't be hard to fix, it's just awkward to work on for those of us who don't ever get to /see/ the blackout.

Closing, as it's a duplicate.

---Alex

**Closed by Alexqw** 2015-11-17 09:41 UTC
Labels: duplicate
