### ISSUE TITLE
Total Access archives not working

### ISSUE THREAD

**Issue by 2upfront** [Alexqw/xbmc-gamepass#167] opened 2015-07-17 20:25 UTC
Hi, this stopped working last week, however I was able to access previous shows. Now I can't access any?

**Comment by Alexqw** [comment] 2015-07-17 20:31
@2upfront Thanks for taking the time to report the problem. The NFL GamePass devs tend to make a lot a changes in July/August, so 'tis the season for breakage.

The soonest I can look into this is a week or so from now. That is, unless someone else beats me to it. ;-)

---Alex

**Comment by kaileu** [comment] 2015-07-18 09:29
Hmm i can't test the current state but the version of my Pull Request is still working.
So maybe it is a Problem with http://gamepass.nfl.com/nflgp/servlets/encryptvideopath can anyone confirm this?
@2upfront as a quick workaround you can merge my the pull request or use the version of my repo https://github.com/kaileu/xbmc-gamepass  but only as long as the Problem is fixed here (i didn't update this version on a regular basis^^)

**Comment by 2upfront** [comment] 2015-07-19 06:34
Ok, thanks

**Comment by 2upfront** [comment] 2015-07-19 08:14
That's solved it for now :)

**Comment by Alexqw** [comment] 2015-08-10 11:01
@2upfront I merged @kaileu's fix with a few small changes. All shows /should/ work now from the main repo.

Let me know if you run into any problems. And thanks again for reporting this bug. :-)

---Alex

**Closed by Alexqw** 2015-08-10 11:01 UTC

**Comment by 2upfront** [comment] 2015-08-10 11:59
Ok, thanks for your work
