### ISSUE TITLE
can't login

### ISSUE THREAD

**Issue by chovy** [Alexqw/xbmc-gamepass#242] opened 2016-07-31 17:19 UTC
My account info hasn't changed since last season.

I can play on web site fine. I'm using NFLGP v0.9.0

also looks like latest is v0.9.1 but its not on the repo yet? When I update, it say only option is v0.9.0

edit: downloaded v0.9.1 manually and it just crashes when I start it. Unfortunately app Log Uploader crashes too.

**Comment by Alexqw** [comment] 2016-08-01 10:04
@chovy Thanks for the bug report; I'm seeing this as well. It looks like they changed their XML response. Looking into it.

---Alex

**Comment by Alexqw** [comment] 2016-08-01 10:05
@chovy Re 0.9.1, I have asked them to push 0.9.1 to the repos, but they havn't gotten around to it yet. It's all on their schedule.

---Alex

**Comment by Alexqw** [comment] 2016-08-01 10:14
@chovy Actually... I can't reproduce the problem. It turns out my credit card info had expired and thus my subscription wasn't renewed. ;-)

Can you provide a debug log so I can see why it's crashing?

---Alex

**Comment by Alexqw** [comment] 2016-08-02 09:13
@chovy Any update?

**Comment by CraigMack69** [comment] 2016-08-02 22:08
I had issues signing in yesterday but not today. But may want to fix the lettering
![untitled](https://cloud.githubusercontent.com/assets/5342680/17347052/b461c030-58c2-11e6-90d9-8d6d0145c2f6.png)

**Comment by Alexqw** [comment] 2016-08-03 06:28
@CraigMack69 Thanks for the positive report about logging in. Sometimes things get weird during renewal. As for the lettering issues, I just fixed that yesterday in master. :-) So if you download the latest from github, all should be well.

---Alex

**Comment by Alexqw** [comment] 2016-08-03 20:48
Closing as this seems to be a non issue. @chovy If you're still experiencing this problem, please reopen running master and include a debug log.

---Alex

**Closed by Alexqw** 2016-08-03 20:48 UTC

**Comment by sigmachi45** [comment] 2016-08-15 20:28
Alex, I am having issues logging in. I have downloaded zip from here and instead of telling me that the logins were incorrect I get a check log report. I can let you on teamviewer if that can help you narrow down the issue im having. 

Thanks

**Comment by Ghoschdi** [comment] 2016-08-15 21:17
There is no reason for posting in multiple threads with the same issue. See your original post for some hints.
