### ISSUE TITLE
60 fps streams

### ISSUE THREAD

**Issue by JetLife010** [Alexqw/xbmc-gamepass#227] opened 2015-12-10 19:00 UTC
Hey guys,
The Xbox One NFL app is offering streams at 720p/60 with 6Mbit. I was wondering if it's possible to implement those in this Add-on. Unfortunately, I'm not able to offer any help on this since I don't own an Xbox One.
Thanks and keep up the good work on this Add-on,
Christoph

**Comment by kaileu** [comment] 2015-12-10 19:11
If i am not wrong the 4500 option are 720p/60fps

Mit freundlichen Grüßen
Kai Leutner

**Comment by dahlSTROM** [comment] 2015-12-10 19:13
As far as I know, only 4.5 Mbit/s is available on the Xbox One. Where did you find the information about 6 Mbit/s?

**Comment by dahlSTROM** [comment] 2015-12-10 21:29
Turns out this is harder than I had anticipated. It's possible to request the streams being used by the Xbox One using the following User-Agent: ```Mozilla/4.0 (Windows NT 6.2; Xbox; Xbox One)```. 

This is throwing 403 Forbidden errors when requesting the .key file though, because it needs additional parameters that I can't for my life figure out how they're being generated.

**Comment by kaileu** [comment] 2015-12-11 02:35
We need someone with a xbox one who makes a wireshark dump :-(
Its a pitty that nfl makes so much diffrence between the devices :(

Mit freundlichen Grüßen
Kai Leutner

**Comment by dahlSTROM** [comment] 2015-12-11 03:21
I've got an Xbox One and made a dump, but I'm not sure how useful it is seeing as there's no way to decrypt the SSL traffic (afaik).

Here's the publishpoint request: (I've removed the URL:s)
```
GET /nflgp/servlets/publishpoint?type=game&gt=live&token=1449796265027.7594adca79ad19e9118858e02fe5e8a4&format=json&mvpd=gampassrewind&id=56695 HTTP/1.1
Accept: */*
User-Agent: Mozilla/4.0 (Windows NT 6.2; Xbox; Xbox One)
If-Modified-Since: Sat, 01 Jan 2000 00:00:01 GMT
Accept-Language: en-US
UA-CPU: AMD64
Accept-Encoding: gzip, deflate
Host: gamepass.nfl.com
Connection: Keep-Alive
Cookie: locale=en_US; iptvpcplatform=nflgp

HTTP/1.1 200 OK
Server: WebServer
Date: Fri, 11 Dec 2015 01:11:05 GMT
Content-Type: text/javascript
Content-Length: 244
Connection: keep-alive
Keep-Alive: timeout=5
Set-Cookie: JSESSIONID=162167477~AB2D8C74DDB931EF05388DA47FECEC77; Path=/nflgp
Pragma: no-cache
Cache-Control: no-cache
Expires: 1

{"path":"[edited out]"}
```

.key request: (edited out URL:s)
```
GET /nlds/nflxbox/*****/as/live/****_hd_6000/20151211000000.m3u8.key?tkn=st=1449792667~exp=1449799867~hmac=0a2f679fbe890b4fb8fadfaf091c5754fa862460 HTTP/1.1
Accept: */*
User-Agent: Mozilla/4.0 (Windows NT 6.2; Xbox; Xbox One)
If-Modified-Since: Sat, 01 Jan 2000 00:00:01 GMT
Accept-Language: en-US
UA-CPU: AMD64
Accept-Encoding: gzip, deflate
Host: nfl-******.xboxlive.com
Connection: Keep-Alive

HTTP/1.1 200 OK
Server: NeuLion Adaptive Streaming Server
Last-Modified: Fri, 11 Dec 2015 00:00:00 GMT
Content-Type: application/octet-stream
Content-Length: 16
Cache-Control: max-age=172733
Expires: Sun, 13 Dec 2015 01:10:00 GMT
Date: Fri, 11 Dec 2015 01:11:07 GMT
Connection: keep-alive

.G@.....2x.nx...GET /nlds/nflxbox/*****/as/live/******_hd_1500/20151211000000.m3u8.key?tkn=st=1449792668~exp=1449799868~hmac=128e513db15a4d668b5c1edad673207c06aafe56 HTTP/1.1
Accept: */*
User-Agent: Mozilla/4.0 (Windows NT 6.2; Xbox; Xbox One)
If-Modified-Since: Sat, 01 Jan 2000 00:00:01 GMT
Accept-Language: en-US
UA-CPU: AMD64
Accept-Encoding: gzip, deflate
Host: nfl-***.xboxlive.com
Connection: Keep-Alive
```

All we need to do is figure out how to generate the ```tkn=st=1449792668~exp=1449799868~hmac=128e513db15a4d668b5c1edad673207c06aafe56``` in the .key URL and how we parse this to ffmpeg.

**Comment by chovy** [comment] 2015-12-11 03:28
ffmpeg part you can just pass the url directly with proper user agent although for me it drops a lot.

**Comment by Alexqw** [comment] 2015-12-11 08:48
@dahlSTROM Thanks for the logs. The ``tkn=st=1449792668~exp=1449799868`` are just the current UNIX time, so that's a non issue. The thing that worries me is the ``hmac=128e413db15a4d668b5c1edad673207c06aafe56``. I'm pretty sure it's a SHA1 [HMAC](https://en.wikipedia.org/wiki/Hash-based_message_authentication_code), which I assume is part of an effort to authenticate the device.

---Alex

**Comment by CraigMack69** [comment] 2016-01-24 03:33
So any progress on this? it would be awesome for the SB

**Comment by chovy** [comment] 2016-01-24 03:54
@dahlSTROM if you want to ping me on skype (aettinger) i can try to play the stream with ffmpeg.
If I figure it out I'll tell you how.

I don't know how I would generate the url myself.

**Comment by denobisipsis** [comment] 2016-03-14 17:08
Hi all,

i think the xbox makes a call to a tokenizer site, maybe a POST, with the key url to get the tokenized url with

tkn=st=1449792668~exp=1449799868~hmac=128e413db15a4d668b5c1edad673207c06aafe56

tkn seems to be token

so you need to make a search in the xbox dump.

**Comment by CraigMack69** [comment] 2016-03-15 23:12
Hey denobis :) It would be awesome to see you around these parts

**Comment by Alexqw** [comment] 2016-03-16 07:08
@denobisipsis But we still need the `hmac` in order to send that request. And, as far as I can see right now, that is the limiting factor here.

However, I'd /love/ it if someone proved me wrong. :-)

---Alex

**Comment by das-land** [comment] 2016-08-08 11:34
Hello,
this hmac thing made me curious. So I searched a little bit through the Internet an this is what i found:
First I search for "gamepass hmac" and found [here](http://www.the-mainboard.com/index.php?threads/cutting-the-cable-free-in-2015.123737/page-15#post-9362240) another stream link with an hmac parameter. Here I was first reading the word akamai. So I continued my search and found [here](https://community.akamai.com/thread/2641#comment-6349) a high level description for the akamai Token. Later i found in [this forum](https://github.com/chrippa/livestreamer/issues/1262#issuecomment-204020303) a [link](http://tp.srgssr.ch/akahd/token?acl=/i/enc13uni_ch@191855/*) with wich is it possible to generate a token in the form of the stream link in the first forum. Unfortunaly this form is not the form that was dumped by [emilsvennesson](https://github.com/Alexqw/xbmc-gamepass/issues/227#issuecomment-163826284), but maybe this works too. So with the words "akamai token" I finally found an [algorithm ](https://gist.github.com/bkad/2938511) to generate a token by yourself.  This algorithm is quite old but I hope he works. 
I hope that some information will help.

**Comment by Alexqw** [comment] 2016-08-08 11:44
@das-land Thanks for looking into this; a lot of good information.

However, from what I'm reading it seems that we still need Game Pass's "client secret", which I /assume/ is shipped within Game Pass's apps rather than supplied dynamically via their servers. However, if anyone can find it being served to the client, that would be wonderful and would make this doable.

---Alex

**Comment by Ghoschdi** [comment] 2016-08-10 12:49
Since i would love to have 60FPS and after searching the net quite a while for an answer, I chatted with the NFL digital/Neulion chaps and tried to find out if they are planning to roll out 60FPS to any addon besides XBOX. Unfortunately there seem to be no plans from their side, as they have an exclusive partnership with Microsoft. The only solution seems to be trying to use IDA (https://www.hex-rays.com/products/ida/index.shtml) to reverse-engineer the NFL Gamepass XBE (hope the one is lucky and gets the C source).

**Comment by Alexqw** [comment] 2016-08-10 13:28
@Ghoschdi Reverse engineering this would run afoul of the DMCA in the US, and GitHub is hosted in the US. So, that is not an option. /If/ the shared secret is somehow provided to the client, then we can do this. but others methods are not ok and would actively endanger the life of this project. Such is the nature of the legal world in which we live. :-/ 

---Alex

**Comment by Ghoschdi** [comment] 2016-08-10 19:23
@Alexqw Totally understand and support that. My information was never meant to cause any legal challenges, just trying to provide neutral inputs to support your investigation. Judging is up to your side.

**Comment by Alexqw** [comment] 2016-08-10 20:24
@Ghoschdi No worries. I was just being clear on how I view this. :-)

I'm going to close this issue because it appears that 60fps is intentionally limited to just the xbox. I expect that if/when if 60fps is expanded to other platforms, that they'll simply add it to the existing stream manifests, which'll be quite easy to support. This issue can be reopened at that time.

Thanks to everyone for digging into this and gathering information. :-)

---Alex

**Closed by Alexqw** 2016-08-10 20:24 UTC

**Comment by chicken--** [comment] 2016-09-09 07:36
Windows 8/10 have an app called "NFL on Windows", I could be wrong but it definitely seemed smoother than the Game Pass website player so it might have been playing at 60fps. Might want to look into that.  It's harder to get working however, it only works through a VPN for me, smart dns doesn't work.

**Comment by aqw** [comment] 2016-09-09 07:40
@chicken-- Again, it's Microsoft, so I imagine they're using the exact same setup as the Xbox. Someone's welcome to look into it, and if they find anything surprising, that's great. I just don't have any access to Windows devices, so I won't be the one to do the sleuthing. ;-)

---Ales

**Comment by kaileu** [comment] 2016-09-09 10:39
yes this is correct. The NFL on Windows App is using the same Servers as the xbox app.
But even if we had the keys the main Problem is the correct algorithm if you would give us the correct algorithm and its only missing the correct key we could dig into it and see if the key is submitted to the client. But we are not aware of all the parts needed.
I assume the token depends on the time the id and the qualkity but thats only a guess.
We have to wait for the android and ios apps till they get the 6k sttreams.

**Comment by sportshd** [comment] 2016-09-11 16:14
From your previous statement about having to wait on android and iOS apps to recieve 60 fps this does not imply users who use windows as there platform  of choice for kodi would be able to receive 60 fps correct.

**Comment by kaileu** [comment] 2016-09-11 16:18
No we are using the methods from the Android and ios for the  
streaming. It doesn't matter on which plattform you are watching as  
long as there is no 6k on ios or android noone could use this on Kodi

Mit freundlichen Grüßen
Kai Leutner

**Comment by sportshd** [comment] 2016-09-15 22:30
After doing some reading it looks like the NFL app on the xbox one is the same app "NFL on Windows" "windows 10" that enables users to watch games in 60 fps.

**Comment by chicken--** [comment] 2016-09-16 02:16
Correct I can confirm that it does indeed play in 60fps, I wasn't sure before because my VPN speed wasn't fast enough to get the 7000kbps 60fps stream but I realized I can disconnect from the VPN once it starts playing and it seems to at least last for a condensed game before I have to re-authorize. I haven't tried it live yet because it's controls are terrible. It's poorly made and doesn't have any of the normal skip back/forward functions the website has :(

**Comment by kaileu** [comment] 2016-09-16 03:33
Yes it is but this doesn't help us.

Mit freundlichen Grüßen
Kai Leutner

**Comment by kaileu** [comment] 2017-08-20 17:59
I got a response from gamepass regarding 60fps:

The video quality is HD native: quality itself is automatically adapted to your speed connection, up to 6000 kpbs. 

We are working to be able to support at least some game video feeds at 60fps per each game week, this with the aim to provide you with the best user experience possible.

I think thats a promising answer :)

**Comment by kaileu** [comment] 2017-08-20 18:30
I got a response from gamepass regarding 60fps:

The video quality is HD native: quality itself is automatically adapted to your speed connection, up to 6000 kpbs. 
We are working to be able to support at least some game video feeds at 60fps per each game week, this with the aim to provide you with the best user experience possible.

**Comment by Ghoschdi** [comment] 2017-08-21 06:50
Cool, question is if they will fall back to 720/60fps like XBox one is doing and why it takes them so long?
