### ISSUE TITLE
Login Not Working

### ISSUE THREAD

**Issue by NiMaD83** [Alexqw/xbmc-gamepass#265] opened 2016-08-24 22:58 UTC
So i watched this last weekends games find on my pc and shield tv with kodi and the add on. 
I go to open it today (on pc) and it gives me a login error every time. I've tried settings to default and again, I've tried uninstalling the add on completely and again same errror. 

But i can log on to it via web browser just fine.

Worked on shield Tv for a few mins but then does anymore :(

**Comment by NiMaD83** [comment] 2016-08-24 23:17
http://pastebin.com/8iJzyHwj

for log

**Comment by kaileu** [comment] 2016-08-25 03:39
You did not activate the Debug Mode.
But let me guess you have a Gamepass International Subscription?
And you are within the US?


Mit freundlichen Grüßen
Kai Leutner

**Comment by NiMaD83** [comment] 2016-08-25 06:12
Well I'm pretty sure debug in the settings was on maybe not. 
Yes GP Int account using in USA with a DNS proxy set to Germany. Hasn't failed yet... watched the last 2 weeks 
Ans shockingly the add on works now. Pretty odd. Was there something in the last update turned off? lol

**Comment by kaileu** [comment] 2016-08-25 06:15
No but these kind of setups cant be supported so if its working now  
you have luck but we cant support this.

Mit freundlichen Grüßen
Kai Leutner

**Comment by NiMaD83** [comment] 2016-08-25 06:30
Umm, why is that?

**Comment by kaileu** [comment] 2016-08-25 06:35
Furthermore, we do not support proxies when used for the purpose of  
getting around Game Pass's region restrictions, as it is against their  
Terms of Service.

Mit freundlichen Grüßen
Kai Leutner

**Comment by Alexqw** [comment] 2016-08-25 06:44
@NiMaD83 Glad to hear the problem is resolved for you. :-)

And @kaileu is right that we do not provide support for proxy setups that circumvent the region restrictions. While not illegal, it is against Game Pass's Terms of Service. And we do not want to invite the ire of the NFL's lawyers here...

Closing.

---Alex

**Closed by Alexqw** 2016-08-25 06:44 UTC
