### ISSUE TITLE
GUI issues

### ISSUE THREAD

**Issue by DevinCook** [Alexqw/xbmc-gamepass#232] opened 2016-04-15 06:24 UTC
I am running Kodi 16.0, 1920x1080, Transparency! skin.

Here is what the GUI looks like:

![screenshot000](https://cloud.githubusercontent.com/assets/2904920/14553018/001178b2-0298-11e6-838c-4117ef4fe93d.png)

**Comment by Alexqw** [comment] 2016-04-15 06:30
@DevinCook Does it look ok when running Confluence? This could be due to the very well known inability to declare our own font.

Also, which version are you running? Is it from the Kodi repos, or from this git repo?

---Alex

**Comment by DevinCook** [comment] 2016-04-15 06:34
Ah yes, it looks correct on Confluence.

Hmm, I guess I need to compromise one way or another.

Thanks

**Comment by Alexqw** [comment] 2016-04-15 06:50
@DevinCook Yeah... it's an annoying bug. :-/ All we can do is wait for Kodi to support custom fonts (or even just one, predictable font) for skinned addons.

Closing; duplicate of #85

---Alex

**Closed by Alexqw** 2016-04-15 06:50 UTC
