### ISSUE TITLE
I cannot get it to login 

### ISSUE THREAD

**Issue by sigmachi45** [Alexqw/xbmc-gamepass#261] opened 2016-08-15 20:02 UTC
I have paid for NFL GP from NFL website. I have attempted to login 15 times and it will not work. I have verified by logging in on my PC with no issues. Can you please assist?

**Comment by sigmachi45** [comment] 2016-08-15 20:05
Forgot to mention I am running Kodi 16.1

**Comment by Ghoschdi** [comment] 2016-08-15 21:19
The zip package from this site will not work out of the box, as it has some unresolved dependencies. Please use the official 0.91 from the repo within Kodi for the easiest way. If the repo version does not work, please activate debug logging for Kodi (system settings) and the GP addon (within addon settings). Afterwards open the Kodi.log and attach it here.

**Comment by sigmachi45** [comment] 2016-08-15 21:27
Now I dont get a check log error. It tells me that login info is incorrect or not valid

**Comment by sigmachi45** [comment] 2016-08-15 21:28
Can you login in using team viewer possibly? im on a windows PC

**Comment by sigmachi45** [comment] 2016-08-15 21:39
14:37:04 T:30828   DEBUG: POParser: loaded 40 strings from file C:\Users\A\AppData\Roaming\Kodi\addons\plugin.video.nfl.gamepass\resources\language\English\strings.po
14:37:04 T:24108   DEBUG: ------ Window Init (DialogOK.xml) ------
14:37:07 T:24108   DEBUG: Keyboard: scancode: 0x1c, sym: 0x000d, unicode: 0x000d, modifier: 0x0
14:37:07 T:24108   DEBUG: CInputManager::OnKey: return (0xf00d) pressed, action is Select
14:37:07 T:24108   DEBUG: ------ Window Deinit (DialogOK.xml) ------
14:37:07 T:30828    INFO: CPythonInvoker(425, C:\Users\A\AppData\Roaming\Kodi\addons\plugin.video.nfl.gamepass\default.py): script aborted

**Comment by sigmachi45** [comment] 2016-08-15 21:41
14:40:23 T:40272  NOTICE: special://profile/ is mapped to: special://masterprofile/
14:40:23 T:40272  NOTICE: -----------------------------------------------------------------------
14:40:23 T:40272  NOTICE: Starting Kodi (16.1 Git:20160424-c327c53). Platform: Windows NT x86 32-bit
14:40:23 T:40272  NOTICE: Using Release Kodi x32 build
14:40:23 T:40272  NOTICE: Kodi compiled Apr 24 2016 by MSVC 180040629 for Windows NT x86 32-bit version 6.0 (0x06000000)
14:40:23 T:40272  NOTICE: Running on TOSHIBA TOSHIBA LX835 with Windows 10, kernel: Windows NT x86 64-bit version 10.0
14:40:23 T:40272  NOTICE: Host CPU: Intel(R) Core(TM) i7-3610QM CPU @ 2.30GHz, 8 cores available
14:40:23 T:40272  NOTICE: Desktop Resolution: 1920x1080 32Bit at 60Hz
14:40:23 T:40272  NOTICE: Running with restricted rights
14:40:23 T:40272  NOTICE: Aero is enabled
14:40:23 T:40272  NOTICE: special://xbmc/ is mapped to: C:\Program Files (x86)\Kodi
14:40:23 T:40272  NOTICE: special://xbmcbin/ is mapped to: C:\Program Files (x86)\Kodi
14:40:23 T:40272  NOTICE: special://masterprofile/ is mapped to: C:\Users\A\AppData\Roaming\Kodi\userdata
14:40:23 T:40272  NOTICE: special://home/ is mapped to: C:\Users\A\AppData\Roaming\Kodi\
14:40:23 T:40272  NOTICE: special://temp/ is mapped to: C:\Users\A\AppData\Roaming\Kodi\cache
14:40:23 T:40272  NOTICE: The executable running is: C:\Program Files (x86)\Kodi\Kodi.exe
14:40:23 T:40272  NOTICE: Local hostname: A-PC
14:40:23 T:40272  NOTICE: Log File is located: C:\Users\A\AppData\Roaming\Kodi\kodi.log
14:40:23 T:40272  NOTICE: -----------------------------------------------------------------------
14:40:23 T:40272  NOTICE: load settings...
14:40:23 T:40272 WARNING: CSettingString: unknown options filler "timezonecountries" of "locale.timezonecountry"
14:40:23 T:40272 WARNING: CSettingString: unknown options filler "timezones" of "locale.timezone"
14:40:23 T:40272  NOTICE: No settings file to load (special://xbmc/system/advancedsettings.xml)
14:40:23 T:40272  NOTICE: Loaded settings file from special://profile/advancedsettings.xml
14:40:23 T:40272  NOTICE: Contents of special://profile/advancedsettings.xml are...
                                            
                                            <advancedsettings>
                                              <network>
                                                <buffermode>2</buffermode>
                                                <cachemembuffersize>629095200</cachemembuffersize>
                                                <curlclienttimeout>15</curlclienttimeout>
                                                <curllowspeedtime>12</curllowspeedtime>
                                                <readbufferfactor>7</readbufferfactor>
                                              </network>
                                            </advancedsettings>
14:40:23 T:40272  NOTICE: Default DVD Player: dvdplayer
14:40:23 T:40272  NOTICE: Default Video Player: dvdplayer
14:40:23 T:40272  NOTICE: Default Audio Player: paplayer
14:40:23 T:40272  NOTICE: Disabled debug logging due to GUI setting. Level 0.
14:40:23 T:40272  NOTICE: Log level changed to "LOG_LEVEL_NORMAL"
14:40:23 T:40272  NOTICE: CMediaSourceSettings: loading media sources from special://masterprofile/sources.xml
14:40:23 T:40272  NOTICE: Loading player core factory settings from special://xbmc/system/playercorefactory.xml.
14:40:23 T:40272  NOTICE: Loaded playercorefactory configuration
14:40:23 T:40272  NOTICE: Loading player core factory settings from special://masterprofile/playercorefactory.xml.
14:40:23 T:40272  NOTICE: special://masterprofile/playercorefactory.xml does not exist. Skipping.
14:40:23 T:32224  NOTICE: Found 2 Lists of Devices
14:40:23 T:32224  NOTICE: Enumerated DIRECTSOUND devices:
14:40:23 T:32224  NOTICE:     Device 1
14:40:23 T:32224  NOTICE:         m_deviceName      : {C58933B6-C305-463A-BFD9-EB20F09FAF30}
14:40:23 T:32224  NOTICE:         m_displayName     : Speakers - Speakers (Realtek High Definition Audio)
14:40:23 T:32224  NOTICE:         m_displayNameExtra: DIRECTSOUND: Speakers (Realtek High Definition Audio)
14:40:23 T:32224  NOTICE:         m_deviceType      : AE_DEVTYPE_PCM
14:40:23 T:32224  NOTICE:         m_channels        : FL,FR
14:40:23 T:32224  NOTICE:         m_sampleRates     : 48000
14:40:23 T:32224  NOTICE:         m_dataFormats     : AE_FMT_FLOAT
14:40:23 T:32224  NOTICE:     Device 2
14:40:23 T:32224  NOTICE:         m_deviceName      : default
14:40:23 T:32224  NOTICE:         m_displayName     : default
14:40:23 T:32224  NOTICE:         m_displayNameExtra:
14:40:23 T:32224  NOTICE:         m_deviceType      : AE_DEVTYPE_PCM
14:40:23 T:32224  NOTICE:         m_channels        : FL,FR
14:40:23 T:32224  NOTICE:         m_sampleRates     : 48000
14:40:23 T:32224  NOTICE:         m_dataFormats     : AE_FMT_FLOAT
14:40:23 T:32224  NOTICE: Enumerated WASAPI devices:
14:40:23 T:32224  NOTICE:     Device 1
14:40:23 T:32224  NOTICE:         m_deviceName      : {C58933B6-C305-463A-BFD9-EB20F09FAF30}
14:40:23 T:32224  NOTICE:         m_displayName     : Speakers - Speakers (Realtek High Definition Audio)
14:40:23 T:32224  NOTICE:         m_displayNameExtra: WASAPI: Speakers (Realtek High Definition Audio)
14:40:23 T:32224  NOTICE:         m_deviceType      : AE_DEVTYPE_PCM
14:40:23 T:32224  NOTICE:         m_channels        : FL,FR
14:40:23 T:32224  NOTICE:         m_sampleRates     : 192000,96000,48000,44100
14:40:23 T:32224  NOTICE:         m_dataFormats     : AE_FMT_S24NE4MSB,AE_FMT_S16NE,AE_FMT_S16LE,AE_FMT_S16BE
14:40:23 T:32224  NOTICE:     Device 2
14:40:23 T:32224  NOTICE:         m_deviceName      : default
14:40:23 T:32224  NOTICE:         m_displayName     : default
14:40:23 T:32224  NOTICE:         m_displayNameExtra:
14:40:23 T:32224  NOTICE:         m_deviceType      : AE_DEVTYPE_PCM
14:40:23 T:32224  NOTICE:         m_channels        : FL,FR
14:40:23 T:32224  NOTICE:         m_sampleRates     : 192000,96000,48000,44100
14:40:23 T:32224  NOTICE:         m_dataFormats     : AE_FMT_S24NE4MSB,AE_FMT_S16NE,AE_FMT_S16LE,AE_FMT_S16BE
14:40:24 T:40272  NOTICE: Running database version Addons20
14:40:24 T:40272  NOTICE: ADDONS: Using repository repository.exodus
14:40:24 T:40272  NOTICE: ADDONS: Using repository repository.eracknaphobia
14:40:24 T:40272  NOTICE: ADDONS: Using repository repository.xunitytalk
14:40:24 T:40272  NOTICE: ADDONS: Using repository superrepo.kodi.jarvis.sports
14:40:24 T:40272  NOTICE: ADDONS: Using repository repository.openeleq
14:40:24 T:40272  NOTICE: ADDONS: Using repository repository.aresproject
14:40:24 T:40272  NOTICE: ADDONS: Using repository superrepo.kodi.jarvis.weather
14:40:24 T:40272  NOTICE: ADDONS: Using repository repository.teamtdb
14:40:24 T:40272  NOTICE: ADDONS: Using repository superrepo.kodi.jarvis.video
14:40:24 T:40272  NOTICE: ADDONS: Using repository repository.rawmaintenance
14:40:24 T:40272  NOTICE: ADDONS: Using repository repository.team.expat
14:40:24 T:40272  NOTICE: ADDONS: Using repository superrepo.kodi.jarvis.repositories
14:40:24 T:40272  NOTICE: ADDONS: Using repository repository.filmkodi.com
14:40:24 T:40272  NOTICE: ADDONS: Using repository repository.noobsandnerds
14:40:24 T:40272  NOTICE: ADDONS: Using repository superrepo.kodi.jarvis.all
14:40:24 T:40272  NOTICE: ADDONS: Using repository repo.natko1412
14:40:24 T:40272  NOTICE: ADDONS: Using repository repository.shani
14:40:24 T:40272  NOTICE: ADDONS: Using repository repository.podgod
14:40:24 T:40272  NOTICE: ADDONS: Using repository repository.q
14:40:24 T:40272  NOTICE: ADDONS: Using repository repository.tknorris.release
14:40:24 T:40272  NOTICE: ADDONS: Using repository repository.Kinkin
14:40:24 T:40272  NOTICE: ADDONS: Using repository repository.xbmchub
14:40:24 T:40272  NOTICE: ADDONS: Using repository repository.VinManJSV
14:40:24 T:40272  NOTICE: ADDONS: Using repository repository.arb
14:40:24 T:40272  NOTICE: ADDONS: Using repository repository.thehighway
14:40:24 T:40272  NOTICE: ADDONS: Using repository repository.mektv
14:40:24 T:40272  NOTICE: ADDONS: Using repository repository.mdrepo
14:40:24 T:40272  NOTICE: ADDONS: Using repository hellyrepo.kodi
14:40:24 T:40272  NOTICE: ADDONS: Using repository repository.xbmc.org
14:40:24 T:40272  NOTICE: ADDONS: Using repository Andy.repository
14:40:24 T:40272  NOTICE: ADDONS: Using repository repository.communityrepo
14:40:24 T:40272  NOTICE: ADDONS: Using repository repository.metalkettle
14:40:24 T:40272  NOTICE: ADDONS: Using repository repository.entertainmentrepobackup
14:40:24 T:40272  NOTICE: ADDONS: Using repository repository.whitecream
14:40:24 T:40272  NOTICE: ADDONS: Using repository repository.istream
14:40:24 T:40272  NOTICE: ADDONS: Using repository repository.docshadrach
14:40:24 T:40272  NOTICE: ADDONS: Using repository repository.kobra
14:40:24 T:40272  NOTICE: ADDONS: Using repository repository.allsorts
14:40:24 T:40272  NOTICE: Found screen: Generic PnP Monitor on Intel(R) HD Graphics 4000, adapter 0.
14:40:24 T:40272  NOTICE: Primary mode: 1920x1080@ 60.00 - Full Screen
14:40:24 T:40272  NOTICE: Additional mode: 320x200@ 60.00 - Full Screen
14:40:24 T:40272  NOTICE: Previous line repeats 2 times.
14:40:24 T:40272  NOTICE: Additional mode: 320x240@ 60.00 - Full Screen
14:40:24 T:40272  NOTICE: Previous line repeats 2 times.
14:40:24 T:40272  NOTICE: Additional mode: 400x300@ 60.00 - Full Screen
14:40:24 T:40272  NOTICE: Previous line repeats 2 times.
14:40:24 T:40272  NOTICE: Additional mode: 512x384@ 60.00 - Full Screen
14:40:24 T:40272  NOTICE: Previous line repeats 2 times.
14:40:24 T:40272  NOTICE: Additional mode: 640x400@ 60.00 - Full Screen
14:40:24 T:40272  NOTICE: Previous line repeats 2 times.
14:40:24 T:40272  NOTICE: Additional mode: 640x480@ 60.00 - Full Screen
14:40:24 T:40272  NOTICE: Previous line repeats 2 times.
14:40:24 T:40272  NOTICE: Additional mode: 800x600@ 60.00 - Full Screen
14:40:24 T:40272  NOTICE: Previous line repeats 2 times.
14:40:24 T:40272  NOTICE: Additional mode: 1024x768@ 60.00 - Full Screen
14:40:24 T:40272  NOTICE: Previous line repeats 2 times.
14:40:24 T:40272  NOTICE: Additional mode: 1152x864@ 60.00 - Full Screen
14:40:24 T:40272  NOTICE: Previous line repeats 2 times.
14:40:24 T:40272  NOTICE: Additional mode: 1280x600@ 60.00 - Full Screen
14:40:24 T:40272  NOTICE: Previous line repeats 2 times.
14:40:24 T:40272  NOTICE: Additional mode: 1280x720@ 60.00 - Full Screen
14:40:24 T:40272  NOTICE: Previous line repeats 2 times.
14:40:24 T:40272  NOTICE: Additional mode: 1280x768@ 60.00 - Full Screen
14:40:24 T:40272  NOTICE: Previous line repeats 2 times.
14:40:24 T:40272  NOTICE: Additional mode: 1280x800@ 60.00 - Full Screen
14:40:24 T:40272  NOTICE: Previous line repeats 2 times.
14:40:24 T:40272  NOTICE: Additional mode: 1280x960@ 60.00 - Full Screen
14:40:24 T:40272  NOTICE: Previous line repeats 2 times.
14:40:24 T:40272  NOTICE: Additional mode: 1280x1024@ 60.00 - Full Screen
14:40:24 T:40272  NOTICE: Previous line repeats 2 times.
14:40:24 T:40272  NOTICE: Additional mode: 1360x768@ 60.00 - Full Screen
14:40:24 T:40272  NOTICE: Previous line repeats 2 times.
14:40:24 T:40272  NOTICE: Additional mode: 1366x768@ 60.00 - Full Screen
14:40:24 T:40272  NOTICE: Previous line repeats 2 times.
14:40:24 T:40272  NOTICE: Additional mode: 1400x1050@ 60.00 - Full Screen
14:40:24 T:40272  NOTICE: Previous line repeats 2 times.
14:40:24 T:40272  NOTICE: Additional mode: 1440x900@ 60.00 - Full Screen
14:40:24 T:40272  NOTICE: Previous line repeats 2 times.
14:40:24 T:40272  NOTICE: Additional mode: 1600x900@ 60.00 - Full Screen
14:40:24 T:40272  NOTICE: Previous line repeats 2 times.
14:40:24 T:40272  NOTICE: Additional mode: 1680x1050@ 60.00 - Full Screen
14:40:24 T:40272  NOTICE: Previous line repeats 2 times.
14:40:24 T:40272  NOTICE: Additional mode: 1920x1080@ 60.00 - Full Screen
14:40:24 T:40272  NOTICE: Checking resolution 16
14:40:24 T:40272  NOTICE: Running database version Addons20
14:40:24 T:40272  NOTICE: Running database version ViewModes6
14:40:24 T:40272  NOTICE: Running database version Textures13
14:40:24 T:40272  NOTICE: Running database version MyMusic56
14:40:24 T:40272  NOTICE: Running database version MyVideos99
14:40:24 T:40272  NOTICE: Running database version TV29
14:40:24 T:40272  NOTICE: Running database version Epg11
14:40:25 T:40272 WARNING: JSONRPC: Could not parse type "Setting.Details.SettingList"
14:40:25 T:40272  NOTICE: ActiveAE DSP - starting
14:40:25 T:40272   ERROR: CScriptInvocationManager::ExecuteAsync - Not executing non-existing script C:\Users\A\AppData\Roaming\Kodi\addons\script.navi-x\service.py
14:40:25 T:40272  NOTICE: initialize done
14:40:25 T:40272  NOTICE: CJoystick::EnumJoysticksCallback : Enabled Joystick: Airmouse
14:40:25 T:40272  NOTICE: CJoystick::EnumJoysticksCallback : Total Axis: 9 Total Hats: 1 Total Buttons: 15
14:40:25 T:40272  NOTICE: Running the application...
14:40:25 T:40272  NOTICE: starting upnp client
14:40:25 T:40864  NOTICE: ES: Starting UDP Event server on 127.0.0.1:9777
14:40:25 T:40864  NOTICE: UDP: Listening on port 9777
14:40:29 T:41120   ERROR: CImageLoader::DoWork - Direct texture file loading failed for resource://resource.images.weathericons.default/.png
14:40:33 T:40424  NOTICE: Skin Helper Service --> skin helper service version 1.0.90 started
14:40:33 T:40424  NOTICE: Skin Helper Service --> WebService - start helper webservice on port 52307
14:40:34 T:31360  NOTICE: script.grab.fanart: Grab Fanart Service Started
14:40:34 T:26220  NOTICE: Universal - An Addons Toolkit: -watchhistory- -Loading sqlite3 as DB engine version: 3.8.6
14:40:34 T:38008  NOTICE: [SPECTO]: ->----------                PARAMS: {'action': 'service'}
14:40:34 T:38008  NOTICE: [SPECTO]: ->----------                PARAMS2: ?action=service
14:40:34 T:26220  NOTICE: Universal - An Addons Toolkit: -watchhistory- -DELETE FROM watch_history WHERE lastwatched < '2016-07-26'
14:40:44 T:33220  NOTICE: [plugin.video.nfl.gamepass-0.9.1]: script starting
14:40:44 T:33220   ERROR: C:\Users\A\AppData\Roaming\Kodi\addons\script.module.requests\lib\requests\packages\urllib3\util\ssl_.py:315: SNIMissingWarning: An HTTPS request has been made, but the SNI (Subject Name Indication) extension to TLS is not available on this platform. This may cause the server to present an incorrect TLS certificate, which can cause validation failures. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#snimissingwarning.
                                              SNIMissingWarning
14:40:44 T:33220   ERROR: C:\Users\A\AppData\Roaming\Kodi\addons\script.module.requests\lib\requests\packages\urllib3\util\ssl_.py:120: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#insecureplatformwarning.
                                              InsecurePlatformWarning
14:40:45 T:33220  NOTICE: [plugin.video.nfl.gamepass-0.9.1]: login failed

**Comment by sigmachi45** [comment] 2016-08-15 22:39
Was that what you needed?

**Comment by justinro** [comment] 2016-08-16 00:02
I am also getting a login failed error, and have confirmed my account/VPN setup works with Gamepass in both the browser and Windows 10 native app (and I'm using the 0.9.1 version from the repo)

Log File:
http://pastebin.com/raw/YpLRtf8c

**Comment by sigmachi45** [comment] 2016-08-16 00:44
I am hoping someone can help me soon Justin. I need to get this fixed before Thursday :) cant miss football.

**Comment by CraigMack69** [comment] 2016-08-16 01:53
I dont see what your problem is guys. Notice i show the time and date in the image to show it.
![untitled](https://cloud.githubusercontent.com/assets/5342680/17685505/8cb8ea98-6319-11e6-807f-f52bba6d4704.png)

**Comment by sigmachi45** [comment] 2016-08-16 01:59
Obviously me and the other guy has something wrong with dependencies and don't know what to do.  I have signed in multiple times and it constantly says my login info is wrong but if I login anywhere else but kodi the same info logs me in.

**Comment by Ghoschdi** [comment] 2016-08-16 06:34
@justinro : I do not even see an login failed message in your log? 
@sigmachi45 + @justinro : Both uninstall the repo 0.91 version, grab the latest master version from this github and the attached script module m3u8 below, in kodi install first the m3u8 from the zip, it will fetch a dep and afterwards install the GP via zip.. Tell me if this solved your issue.

[script.module.m3u8-0.2.2.zip](https://github.com/Alexqw/xbmc-gamepass/files/419661/script.module.m3u8-0.2.2.zip)

**Comment by Alexqw** [comment] 2016-08-16 06:42
@justinro You need to enable debugging in both Kodi /and/ the addon. Then please post a log.

@sigmachi45 You need to calm down. Commenting in two different issues and sending me a private email all in the space of a few hours is inappropriate and rude. You are experiencing issue #183 This is due to a bug in Python that we have no control over. You're on Windows, so your copy of Python is bundled with Kodi. Newer (alpha) versions of Kodi come with an updated copy of Python. Most users don't get this error because 1) they don't use a proxy, which forces a redirect, which is what causes this TLS issue 2) their system provides a newer version of Python.

---Alex

**Comment by kaileu** [comment] 2016-08-16 06:43
In both cases are ssl sni errors.
Maybe this causes errors.

Mit freundlichen Grüßen
Kai Leutner

**Comment by sigmachi45** [comment] 2016-08-16 16:18
so is there a fix? I would pay someone $50 to logon to teamviewer and fix the issues for me. Anyone open to do such for me?

**Comment by Ghoschdi** [comment] 2016-08-16 17:01
@sigmachi45: Not necessary - try using the new krypton Alpha 3 for Windows here http://mirrors.kodi.tv/snapshots/win32/kodi-17.0-Krypton_alpha3.exe . Pretty straight forward update via the installer. I use it on one of my windows boxes and it is pretty stable.

**Comment by Alexqw** [comment] 2016-08-16 17:01
@sigmachi45 Basically, you have these options:
1) Stick with Windows and run Kodi 17.x --- which is unstable
2) Switch to another OS (pick nearly any linux distro) which'll use its own, more modern copy of Python.
3) Stop using a proxy
4) Upgrade to 17.x and then downgrade back to 16.x (this should not work at all, but it "worked" for someone else. Highly suspicious, but who knows; maybe some cached .po is leftover and magically fixes it.

If someone is interested in taking his teamviewer offer, feel free to jump on it.

---Alex

**Comment by sigmachi45** [comment] 2016-08-16 17:03
I really hope someone is willing to help and take the money. I am not smart when it comes to this crap. I am new to kodi and I jsut want everything to work. I dont understand this debugging cut and paste stuff ect. If there is a fix Im completly willing to pay you for your time anyone. I jsut need it to work before the weekend.

**Comment by justinro** [comment] 2016-08-16 17:41
@kaileu @Alexqw 
Thanks for the suggestions guys, and apologies for not having my debugging on (rookie mistake)! 

I tried the above tricks (uninstalling, installing the dependencies separately and then re-installing the latest) and still getting the login error unfortunately. Wouldn't mind updating to Krypton if necessary (though it breaks other addons for me), or PM'ing my login details to one of you, though the SNI SSL errors do seem odd.

Here's the log file with actual logging info:
[](http://pastebin.com/raw/bWgjNu3p)

**Comment by Ghoschdi** [comment] 2016-08-16 17:49
@justinro: Cannot comment on your breaking addons as mine all run on the Krypton branch, but the A3 really runs stable and performant now also on my Shield TV. Maybe try upgrading, running and if it works, downgrading via the installer back to 16.1 as Alex suggested. Did this tons of time now on my windows machine and never had issues afterwards.

**Comment by justinro** [comment] 2016-08-16 21:19
@Ghoschdi: Updated to Krypton and it worked!! I'll stick to 17.x from now on, worth it for this addon alone. Thanks guys!!

**Comment by sigmachi45** [comment] 2016-08-17 00:00
I dont understand. I downloaded 17. krypton and it wouldnt work there either. 

Please Im paying money to whom ever can fix this for me

**Comment by Alexqw** [comment] 2016-08-17 06:31
@justinro Glad it's working for you. :-)

@sigmachi45 I'm sorry to hear you're still having problems. In general, the environment here is helping people to help themselves. That isn't to say that no one will be willing to take your money, it's just not generally the primary motivation of people who spend time around here.

If you're interested in troubleshooting this, and now that you've upgraded to 17.x, you should include a new debug log.

---Alex

**Comment by antbutler17** [comment] 2016-08-17 06:52
I am having the same problem. Running Kodi 16.1 on Mac. Like @sigmachi45 my Game Pass International works on any other platform. Also tried on Krypton 17.x and I got the same 'login failed' message. Here is my log: http://pastebin.com/w2Qw044h

Any help would be greatly appreciated.

**Comment by kaileu** [comment] 2016-08-17 06:55
@Antbutler17 your Proxy didn't work.
You are in the us and trying to use gamepass international.

Mit freundlichen Grüßen
Kai Leutner

**Comment by Alexqw** [comment] 2016-08-17 06:55
@antbutler17 Your log shows you're running 16.1. You'll need to attach your 17.x log.

---Alex

**Comment by antbutler17** [comment] 2016-08-17 07:07
Here is my log for 17.x: http://pastebin.com/ZNnYXN2P

**Comment by kaileu** [comment] 2016-08-17 07:11
@antbutler17
                                                      
<isGPDomestic>true</isGPDomestic>
                                                      
<nflAccessToken></nflAccessToken>
                                                      
<nflConcurrentId></nflConcurrentId>

                                                 <country>US</country>

This means your are in the US and trying to login to International  
Gamepass that didn't work out.
You have to correct your Proxy/vpn or buy Gamepass Domestic.

Mit freundlichen Grüßen
Kai Leutner

**Comment by antbutler17** [comment] 2016-08-17 07:54
How do I correct my proxy? I have a VPN running on my Mac.

**Comment by kaileu** [comment] 2016-08-17 07:57
Your vpn is not working.
I am not a Mac user but your problem is not addon related. Why Kodi  
didn't use your proxy i don't know.

Mit freundlichen Grüßen
Kai Leutner

**Comment by sigmachi45** [comment] 2016-08-17 13:36
I hate to saying t but I don't think this addon works at all.  The only screen shots all come off of a pic with the x in the upper right corner to close down a window. There are no other apps in kodi that have this much issue when installing.  And the dev team always makes it out to be an issue with your device. I've offered money for them to fix proxy or whatever else they blame the issue on when really it's a busted addon that they need to work on. Seems as if no other dev team has the issue of getting an addon to work in kodi except this one. GamePass is a scam and incompatence within the dev team is off the charts

**Comment by Alexqw** [comment] 2016-08-17 13:40
@sigmachi45 please take your griping elsewhere.

---Alex

**Comment by Alexqw** [comment] 2016-08-17 13:40
Closing

**Closed by Alexqw** 2016-08-17 13:40 UTC

**Comment by Ghoschdi** [comment] 2016-08-17 13:43
Can only praise the attitude and willingness of the developers on this "free of charge" and "not affiliated at all with the GamePass service" group of developers...As a very happy user, i am speechless because of this comment :(

**Comment by Alexqw** [comment] 2016-08-17 13:44
@Ghoschdi No worries. Welcome to the internet. ;-) Thanks for the props though. :-)

**Comment by Ghoschdi** [comment] 2016-08-17 13:47
@Alexqw: Welcome, was a long time dev for quite some interesting projects (sadly no python experience) and encountered a lot of these "nice people". But i am always speechless how ungrateful and off the mark such things are. As said, no experience with python and missing time to digg myself in, but really would love to give something back.

**Comment by BaumSchorle** [comment] 2016-08-17 13:52
Just for documentation purposes:

It's against the Terms and Conditions of GamePass to access international version from the US:

```
Access to certain of the Subscription Products is limited to residents of certain geographical territories, as follows:

(a) NFL Game Pass (International) is only available to users located outside of the NFL Game Pass International Excluded Territories. You are not authorized to use NFL Game Pass (International) if you are located in any of the NFL Game Pass International Excluded Territories, and you agree not to access or attempt to access NFL Game Pass International from any of the NFL Game Pass International Excluded Territories.
```

@Alexqw Maybe we need to overthing this 'supporting' of these problems related to proxies/vpn/what ever

**Comment by sigmachi45** [comment] 2016-08-17 13:52
Oh bull shit stefan you a part of it and you know it this shit does not work in no way. If it did why would t the dev team just fix the issues on their end so it can be like every other addon install login and work

**Comment by sigmachi45** [comment] 2016-08-17 13:53
Maybe u should create an addon that works!@Alexq

**Comment by Alexqw** [comment] 2016-08-17 13:57
Locking this issue to only those who have commit access as @sigmachi45 is still working on the "play nicely with others"  thing. I don't like locking, but it seems to be the best approach for now.

Moving on....

@Ghoschdi Help is always welcome, regardless of Python experience. For quite a few of the devs here, this is the first non-trivial Python project we've worked on. So don't be afraid about that. I can't say the code is terribly Pythonic (though we're getting better, as time goes on).

As for lack of time... I can't say I can help with that. ;-)

@BaumSchorle Yeah, we've been getting so many of these bug reports as of late. At it's core, it is a Python bug, but I agree, it is against the ToS and makes troubleshooting a real pain.

This might be something that could go into an [issue template](https://github.com/blog/2111-issue-and-pull-request-templates).

---Alex

**Comment by BaumSchorle** [comment] 2016-08-17 14:17
@Alexqw I thnik we need to make it clear, that it is against ToS and we don't want to support it. Maybe we need to think about throwing the proxy settings out, if this keeps going on.

As this addon gets more and more popular the neulion and/or the nfl will get aware of this and could shut this thing down. :-1:

**Comment by Alexqw** [comment] 2016-08-17 15:10
@BaumSchorle I agree we should make it clear and should close any issues that mention it. That's my fault as much as anyone's for becoming less strict about this.

The question becomes, how strict should we be? It's one thing to close issues, but do we want to purge any comments that even mention it? My hope is that if/when Game Pass discovers us, that they'll be ok with us. Having not only the devs be squeeky clean but also the user created issues goes a long way toward that. Though it does feel draconian. Thoughts?

I think the proxy setting should stay for now, as there are some network setups which do require proxies *and* have nothing to do with bypassing region restrictions. This is obviously uncommon, but they do exist.

I'll add an issue template tomorrow.

---Alex
