### ISSUE TITLE
Logging into NFL Game Pass failed

### ISSUE THREAD

**Issue by HenioH** [Alexqw/xbmc-gamepass#225] opened 2015-12-01 00:08 UTC
I keep getting "Logging into NFL Game Pass failed". I have an Int Game Pass Account. Tried uninstalling then reinstalling from the current GitHub link and still same issue.

Kodi.log: http://pastebin.com/JR4AXatB

**Comment by BaumSchorle** [comment] 2015-12-01 06:43
@HenioH Seems like there is something wrong with your subscription, because we get this as a response from the GamePass servers: <code>noproductaccess</code>

It also says that you are US based and a Domestic GamePass user:

<isGPDomestic>true</isGPDomestic>                                       
<country>US</country>

Seems like the addon is not broke and works like expected. Please verify that you can access GamePass on their web-site.

**Comment by Alexqw** [comment] 2015-12-04 14:22
@HenioH Any update on this? Otherwise I plan to close this soon as I'm pretty sure @BaumSchorle is right.

---Alex

**Comment by Alexqw** [comment] 2015-12-07 15:06
@HenioH Closing. Please reopen if you still have this problem with the latest code.

---Alex

**Closed by Alexqw** 2015-12-07 15:06 UTC

**Comment by dshenderson** [comment] 2016-01-11 09:35
I am having the exact same problem. I'm able to log into Game Pass on my laptop to watch games, but not through the addon.

**Comment by kaileu** [comment] 2016-01-11 09:38
dshenderson  please post a logfile

**Comment by dshenderson** [comment] 2016-01-11 10:00
09:54:16 T:139833722468224   DEBUG: ProcessMouse: trying mouse action leftclick
09:54:16 T:139833288423168  NOTICE: Thread LanguageInvoker start, auto delete: false
09:54:16 T:139833288423168    INFO: initializing python engine.
09:54:16 T:139833288423168   DEBUG: CPythonInvoker(4, /storage/.kodi/addons/plugin.video.nfl.gamepass/default.py): start processing
09:54:16 T:139833288423168  NOTICE: -->Python Interpreter Initialized<--
09:54:16 T:139833288423168   DEBUG: CPythonInvoker(4, /storage/.kodi/addons/plugin.video.nfl.gamepass/default.py): the source file to load is "/storage/.kodi/addons/plugin.video.nfl.gamepass/default.py"
09:54:16 T:139833288423168   DEBUG: CPythonInvoker(4, /storage/.kodi/addons/plugin.video.nfl.gamepass/default.py): setting the Python path to /storage/.kodi/addons/plugin.video.nfl.gamepass:/storage/.kodi/addons/script.module.requests/lib:/storage/.kodi/addons/script.module.xmltodict/lib:/usr/lib/python27.zip:/usr/lib/python2.7:/usr/lib/python2.7/plat-linux2:/usr/lib/python2.7/lib-tk:/usr/lib/python2.7/lib-old:/usr/lib/python2.7/lib-dynload:/usr/lib/python2.7/site-packages:/usr/lib/python2.7/site-packages/PIL:/usr/lib/python2.7/site-packages/gtk-2.0
09:54:16 T:139833288423168   DEBUG: CPythonInvoker(4, /storage/.kodi/addons/plugin.video.nfl.gamepass/default.py): entering source directory /storage/.kodi/addons/plugin.video.nfl.gamepass
09:54:16 T:139833288423168   DEBUG: CPythonInvoker(4, /storage/.kodi/addons/plugin.video.nfl.gamepass/default.py): instantiating addon using automatically obtained id of "plugin.video.nfl.gamepass" dependent on version 2.19.0 of the xbmc.python api
09:54:16 T:139833288423168  NOTICE: [pigskin]: Debugging enabled.
09:54:16 T:139833288423168  NOTICE: [pigskin]: Python Version: 2.7.3 (default, Mar 31 2015, 22:10:50)
                                            [GCC 4.9.2]
09:54:16 T:139833288423168  NOTICE: [plugin.video.nfl.gamepass-0.8.1]: script starting
09:54:16 T:139833288423168  NOTICE: [pigskin]: Request URL: http://gamepass.nfl.com/nflgp/servlets/simpleconsole
09:54:16 T:139833288423168  NOTICE: [pigskin]: Headers: None
09:54:17 T:139833288423168  NOTICE: [pigskin]: Response code: 302
09:54:17 T:139833288423168  NOTICE: [pigskin]: Response:
09:54:17 T:139833288423168  NOTICE: [pigskin]: No user name detected in Game Pass response.
09:54:17 T:139833288423168  NOTICE: [pigskin]: Not (yet) logged into international
09:54:17 T:139833288423168  NOTICE: [pigskin]: Request URL: https://gamepass.nfl.com/nflgp/secure/nfllogin
09:54:17 T:139833288423168  NOTICE: [pigskin]: Headers: None
09:54:17 T:139833288423168   ERROR: /storage/.kodi/addons/script.module.requests/lib/requests/packages/urllib3/util/ssl_.py:315: SNIMissingWarning: An HTTPS request has been made, but the SNI (Subject Name Indication) extension to TLS is not available on this platform. This may cause the server to present an incorrect TLS certificate, which can cause validation failures. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#snimissingwarning.
                                              SNIMissingWarning
09:54:17 T:139833288423168   ERROR: /storage/.kodi/addons/script.module.requests/lib/requests/packages/urllib3/util/ssl_.py:120: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#insecureplatformwarning.
                                              InsecurePlatformWarning
09:54:20 T:139833288423168  NOTICE: [pigskin]: Response code: 200
09:54:20 T:139833288423168  NOTICE: [pigskin]: Response: <?xml version="1.0" encoding="UTF-8"?>
                                            <result>
                                               
                                                    <code>loginsuccess</code>
                                               
                                               
                                                    <data>
                                                       
                                                            <userName><![CDATA[usernameredacted]]></userName>
                                                       
                                                            <givenName><![CDATA[givennameredacted]]></givenName>
                                                       
                                                    </data>
                                               
                                            </result>
09:54:20 T:139833288423168  NOTICE: [pigskin]: Request URL: http://gamepass.nfl.com/nflgp/servlets/simpleconsole
09:54:20 T:139833288423168  NOTICE: [pigskin]: Headers: None
09:54:20 T:139833288423168  NOTICE: [pigskin]: Response code: 302
09:54:20 T:139833288423168  NOTICE: [pigskin]: Response:
09:54:20 T:139833288423168  NOTICE: [pigskin]: No user name detected in Game Pass response.
09:54:20 T:139833288423168  NOTICE: [plugin.video.nfl.gamepass-0.8.1]: login failed
09:54:20 T:139833288423168   DEBUG: POParser: loaded 40 strings from file /storage/.kodi/addons/plugin.video.nfl.gamepass/resources/language/English/strings.po
09:54:20 T:139833722468224   DEBUG: ------ Window Init (DialogOK.xml) ------
09:54:25 T:139833722468224   DEBUG: Keyboard: scancode: 0x09, sym: 0x001b, unicode: 0x001b, modifier: 0x0
09:54:25 T:139833722468224   DEBUG: OnKey: escape (0xf01b) pressed, action is PreviousMenu
09:54:25 T:139833722468224   DEBUG: ------ Window Deinit (DialogOK.xml) ------
09:54:25 T:139833288423168    INFO: CPythonInvoker(4, /storage/.kodi/addons/plugin.video.nfl.gamepass/default.py): script aborted
09:54:25 T:139833288423168    INFO: Python script stopped
09:54:25 T:139833288423168   DEBUG: Thread LanguageInvoker 139833288423168 terminating

**Comment by dshenderson** [comment] 2016-01-11 10:02
Here's the logfile:

[kodilogfile.txt](https://github.com/Alexqw/xbmc-gamepass/files/85528/kodilogfile.txt)

**Comment by dshenderson** [comment] 2016-01-18 00:33
Any update on this? This is still an existing issue. Thanks.

**Comment by kaileu** [comment] 2016-01-19 17:09
pigskin]: No user name detected in Game Pass response.
09:54:20 T:139833288423168  NOTICE: [plugin.video.nfl.gamepass-0.8.1]: login failed


So it seems to be an error with your credentials or your connection but enable the debug information.

**Comment by dshenderson** [comment] 2016-01-19 21:15
Thank you, @kaileu, for responding.

If you look a few lines above the lines you copied, you'll see the credentials are sent, and as the same credentials successfully log me in via the Flash app on my laptop, I don't think that's it.

Not sure what you mean by my connection. I've got a stable and very fast network connection. What about the connection do you think it might be?

One thing that caught my eye is that the credentials are being sent as CDATA, but that wasn't the case with HenioH's credentials. Could this be the source of the problem and, if so, what could be causing that?

**Comment by kaileu** [comment] 2016-01-19 21:21
The problem is that the error is not shown the line i posted references a file which we cant see because you didn't turn on the addon debbugging and the kodi debugging features.
You have to enable it and repost a log.
If you can upload it via http://xbmclogs.com it would be easier to read.

**Comment by dshenderson** [comment] 2016-01-20 14:29
@kaileu, debugging should have been turned on. I've turned it on again and reposted log: http://xbmclogs.com/pjs4uyazi.  Thanks.

**Comment by dahlSTROM** [comment] 2016-01-20 17:01
What kind of subscription do you have? Could you please login to Game Pass using your browser, go to http://gamepass.nfl.com/nflgp/servlets/simpleconsole and post your XML response (press Ctrl+U).

**Comment by dshenderson** [comment] 2016-01-20 17:23
<?xml version="1.0" encoding="UTF-8"?>
<result>
	<config>
		<locProgramImage>http://smb.cdnak.md.neulion.com/u/nfl/nfl/thumbs/</locProgramImage>
		<locChannelVideo></locChannelVideo>
		<locCategoryImage>flex/images</locCategoryImage>
		
			
			<locEDL>http://neulionms-a.akamaihd.net/fs/nfl/nfl/edl/nflgp/</locEDL>
		
		<locQOS>http://nlqosdrecv01.neulion.com/msdrecv/ProxyBean</locQOS>
		
	</config>
	<currentWeek>220</currentWeek>
	<currentSeason>2015</currentSeason>
	<currentDate d="Wed" tzOffset="-5">2016-01-20T12:22:55.632</currentDate>
	
		
		
			<statsFeedPrefix>http://neulionms-a.akamaihd.net/fs/nfl/nfl/stats/boxscores/</statsFeedPrefix>
			<scoresFeedPrefix>http://neulionms-a.akamaihd.net/fs/nfl/nfl/stats/scores/</scoresFeedPrefix>
			<pbpFeedPrefix>http://neulionms-a.akamaihd.net/fs/nfl/nfl/edl/nflgr/</pbpFeedPrefix>
			<searchPrefix><![CDATA[http://smbsolr.cdnak.neulion.com/solr/nflplay/select?fl=*&rows=200&q=]]></searchPrefix>
			<messageFeedPrefix><![CDATA[http://smb.cdnak.neulion.com/fs/nfl/nfl/appmessage/]]></messageFeedPrefix>
		
	
	<fantasyPrefix><![CDATA[http://subs.api.fantasy.nfl.com/]]></fantasyPrefix>
	<nflConcurrencyUrl><![CDATA[https://api.nfl.com/v1/concurrentusers?]]></nflConcurrencyUrl>
	
	
		
			<user>
				<userName><![CDATA[operaman22]]></userName>
				<firstName><![CDATA[Derek]]></firstName>
			</user>
			
			
				
					
						
							<subscription expiration="2016-08-01T00:00:00.000">SEASON_PLUS</subscription>
						
						
					
				
				
			
			
				
				
			
			
		
		
		
	
	
	<country>GB</country>
	
	
	<ukrz>true</ukrz>
	
		<rzPhase>pre</rzPhase>
	
	<redZoneCats>
		
			<cat season="2011" id="116" />
		
			<cat season="2014" id="221" />
		
			<cat season="2015" id="248" />
		
			<cat season="2012" id="149" />
		
			<cat season="2013" id="182" />
		
	</redZoneCats>
	<nflnShows>
		<show>
			<name><![CDATA[A FOOTBALL LIFE]]></name>
			<img>shows/afootballlife.png</img>
			<seasons>
				<season catId="249"><![CDATA[SEASON 2015]]></season>
				<season catId="218"><![CDATA[SEASON 2014]]></season>
				<season catId="186"><![CDATA[SEASON 2013]]></season>
				<season catId="154"><![CDATA[SEASON 2012]]></season>
			</seasons>
		</show>
		<show>
			<name><![CDATA[HALL OF FAME]]></name>
			<img>shows/halloffame.png</img>
			<seasons>
				<season catId="250"><![CDATA[SEASON 2015]]></season>
				<season catId="222"><![CDATA[SEASON 2014]]></season>
			</seasons>
		</show>
		<show>
			<name><![CDATA[HARD KNOCKS]]></name>
			<img>shows/hardknocks.png</img>
			<seasons>
				<season catId="251"><![CDATA[SEASON 2015]]></season>
				<season catId="220"><![CDATA[SEASON 2014]]></season>
				<season catId="223"><![CDATA[SEASON 2013]]></season>
			</seasons>
		</show>
		<show>
			<name><![CDATA[NFL FILMS PRESENTS]]></name>
			<img>shows/nflfilms.png</img>
			<seasons>
				<season catId="187"><![CDATA[SEASON 2013]]></season>
			</seasons>
		</show>
		<show>
			<name><![CDATA[NFL GAMEDAY]]></name>
			<img>shows/gameday.png</img>
			<seasons>
				<season catId="252"><![CDATA[SEASON 2015]]></season>
				<season catId="212"><![CDATA[SEASON 2014]]></season>
				<season catId="179"><![CDATA[SEASON 2013]]></season>
				<season catId="146"><![CDATA[SEASON 2012]]></season>
				<season catId="113"><![CDATA[SEASON 2011]]></season>
				<season catId="85"><![CDATA[SEASON 2010]]></season>
			</seasons>
		</show>
		<show>
			<name><![CDATA[NFL HONORS]]></name>
			<img>shows/halloffame.png</img>
			<seasons>
				<season catId="253"><![CDATA[SEASON 2015]]></season>
				<season catId="224"><![CDATA[SEASON 2014]]></season>
			</seasons>
		</show>
		<show>
			<name><![CDATA[NFL TOTAL ACCESS]]></name>
			<img>shows/totalaccess.png</img>
			<seasons>
				<season catId="254"><![CDATA[SEASON 2015]]></season>
				<season catId="214"><![CDATA[SEASON 2014]]></season>
				<season catId="181"><![CDATA[SEASON 2013]]></season>
				<season catId="148"><![CDATA[SEASON 2012]]></season>
				<season catId="115"><![CDATA[SEASON 2011]]></season>
				<season catId="87"><![CDATA[SEASON 2010]]></season>
			</seasons>
		</show>
		<show>
			<name><![CDATA[PLAYBOOK]]></name>
			<img>shows/playbook.png</img>
			<seasons>
				<season catId="255"><![CDATA[SEASON 2015]]></season>
				<season catId="213"><![CDATA[SEASON 2014]]></season>
				<season catId="180"><![CDATA[SEASON 2013]]></season>
				<season catId="147"><![CDATA[SEASON 2012]]></season>
				<season catId="114"><![CDATA[SEASON 2011]]></season>
				<season catId="86"><![CDATA[SEASON 2010]]></season>
			</seasons>
		</show>
		<show>
			<name><![CDATA[SOUND FX]]></name>
			<img>shows/soundfx.png</img>
			<seasons>
				<season catId="256"><![CDATA[SEASON 2015]]></season>
				<season catId="215"><![CDATA[SEASON 2014]]></season>
				<season catId="183"><![CDATA[SEASON 2013]]></season>
				<season catId="150"><![CDATA[SEASON 2012]]></season>
				<season catId="118"><![CDATA[SEASON 2011]]></season>
			</seasons>
		</show>
		<show>
			<name><![CDATA[SUPER BOWL ARCHIVES]]></name>
			<img>shows/superbowl.png</img>
			<seasons>
				<season catId="117"><![CDATA[ARCHIVES]]></season>
			</seasons>
		</show>
		<show>
			<name><![CDATA[THE TIMELINE]]></name>
			<img>shows/timeline.png</img>
			<seasons>
				<season catId="264"><![CDATA[SEASON 2015]]></season>
			</seasons>
		</show>
		<show>
			<name><![CDATA[TOP 100 PLAYERS]]></name>
			<img>shows/top100players.png</img>
			<seasons>
				<season catId="257"><![CDATA[SEASON 2015]]></season>
				<season catId="217"><![CDATA[SEASON 2014]]></season>
				<season catId="185"><![CDATA[SEASON 2013]]></season>
				<season catId="153"><![CDATA[SEASON 2012]]></season>
				<season catId="121"><![CDATA[SEASON 2011]]></season>
			</seasons>
		</show>
	 </nflnShows>
</result>

**Comment by dahlSTROM** [comment] 2016-01-20 17:32
Well, everything looks fine there... For some reason, you're getting an empty response when requesting the simpleconsole URL from the plugin. Are you using any DNS service/proxy/etc to circumvent the UK blackouts? Could you also try the plugin on your PC to verify that you have the same issue there?

**Comment by chovy** [comment] 2016-01-20 19:23
if you have trouble logging in (ie: it doesn't work at all) try using viperdns.com to see if its a geo-blackout issue.

**Comment by dshenderson** [comment] 2016-01-21 01:01
@dahlSTROM, bingo! It was a DNS issue. I didn't realise my OpenElec box was pointing to the Unblock-Us servers and my laptop wasn't, hence the discrepancy. I fixed this and now the app works. Apologies for taking up everyone's time, and many thanks for your help!
