### ISSUE TITLE
Nfl Redzone

### ISSUE THREAD

**Issue by sportshd** [Alexqw/xbmc-gamepass#211] opened 2015-09-27 15:57 UTC
I'm on the addon and I don't see the Redzone channel option. Does it come on when games start?

**Comment by Alexqw** [comment] 2015-09-27 16:12
@sportshd Yeah, it only comes on once RedZone starts broadcasting. There's been a few forum comments indicating that perhaps our RedZone detection isn't working. Once it starts, I'll take a look, make sure it's working, and if not, push a fix to master.

---Alex

**Comment by sportshd** [comment] 2015-09-27 16:23
Thanks.

**Comment by Alexqw** [comment] 2015-09-27 17:03
Works great for me. It should be up now.

---Alex

**Comment by Alexqw** [comment] 2015-09-27 17:07
I'm closing this, since it seems to be working just fine. If you have any problems, feel free to re-open.

---Alex

**Comment by sportshd** [comment] 2015-09-27 17:32
I'm not seeing the option for redzone. All I see is 

Gamepass.    NFLNetwork.    Along the top.

If I click on game pass I see the games bu t no redzone. If I click on NFL network then the option to see the NFL network comes up but nothing regarding redzone.

**Comment by Alexqw** [comment] 2015-09-27 18:27
Close the addon, and go into it again. It should be under the NFL Network. It'll be on the right, next to NFL Network Live.

---Alex

**Comment by Alexqw** [comment] 2015-09-27 18:43
If you are still having problems, please attach a debug log. The sooner you do this, the better. We can only work on/fix this problem while RedZone is broadcasting. This is (obviously) a small window.

I have reopened this issue, but will close it if I receive no response.

---Alex

**Comment by sportshd** [comment] 2015-09-27 19:10
Its not there I will try and  attach a log file in a bit thanks.

**Comment by sportshd** [comment] 2015-09-27 20:56
Where is the debug log?

**Comment by sportshd** [comment] 2015-09-27 21:31
I'm not sure if this is what you are looking for but I did a cut and paste
of part of the kodi log

















                                            










<isGPDomestic>true</isGPDomestic>


<nflAccessToken>eyJhbGciOiJIUzI1NiJ9.eyJ1c2VybmFtZSI6InRtZW5kb3phNjYiLCJkZXZpY2VJZCI6bnVsbCwiY2xpZW50SWQiOiJuZXVsaW9uIiwiZXhwIjoxNDQzMzkwNjYzLCJpYXQiOjE0NDMzODcwNjN9.xDU-Fc9k9M4XLngzRuo5z7OTav5GdPMy6519ITmlTvM</nflAccessToken>


<nflConcurrentId>4c8eff80-25a1-3de0-259c-f3297f000001</nflConcurrentId>



                                            <country>US</country>





                                            <ukrz>true</ukrz>



                                            <rzPhase>none_in</rzPhase>



                                            <redZoneCats>



                                            <cat season="2011" id="116" />



                                            <cat season="2014" id="221" />



                                            <cat season="2015" id="248" />



                                            <cat season="2012" id="149" />



                                            <cat season="2013" id="182" />



                                            </redZoneCats>

                                            <nflnShows>

                                            <show>

                                            <name><![CDATA[A FOOTBALL
LIFE]]></name>


<img>shows/afootballlife.png</img>

                                            <seasons>

                                            <season
catId="249"><![CDATA[SEASON 2015]]></season>

                                            <season
catId="218"><![CDATA[SEASON 2014]]></season>

                                            <season
catId="186"><![CDATA[SEASON 2013]]></season>

                                            <season
catId="154"><![CDATA[SEASON 2012]]></season>

                                            </seasons>

                                            </show>

                                            <show>

                                            <name><![CDATA[HALL OF
FAME]]></name>

                                            <img>shows/halloffame.png</img>

                                            <seasons>

                                            <season
catId="250"><![CDATA[SEASON 2015]]></season>

                                            <season
catId="222"><![CDATA[SEASON 2014]]></season>

                                            </seasons>

                                            </show>

                                            <show>

                                            <name><![CDATA[HARD
KNOCKS]]></name>

                                            <img>shows/hardknocks.png</img>

                                            <seasons>

                                            <season
catId="251"><![CDATA[SEASON 2015]]></season>

                                            <season
catId="220"><![CDATA[SEASON 2014]]></season>

                                            <season
catId="223"><![CDATA[SEASON 2013]]></season>

                                            </seasons>

                                            </show>

                                            <show>

                                            <name><![CDATA[NFL FILMS
PRESENTS]]></name>

                                            <img>shows/nflfilms.png</img>

                                            <seasons>

                                            <season
catId="187"><![CDATA[SEASON 2013]]></season>

                                            </seasons>

                                            </show>

                                            <show>

                                            <name><![CDATA[NFL
GAMEDAY]]></name>

                                            <img>shows/gameday.png</img>

                                            <seasons>

                                            <season
catId="252"><![CDATA[SEASON 2015]]></season>

                                            <season
catId="212"><![CDATA[SEASON 2014]]></season>

                                            <season
catId="179"><![CDATA[SEASON 2013]]></season>

                                            <season
catId="146"><![CDATA[SEASON 2012]]></season>

                                            <season
catId="113"><![CDATA[SEASON 2011]]></season>

                                            <season
catId="85"><![CDATA[SEASON 2010]]></season>

                                            </seasons>

                                            </show>

                                            <show>

                                            <name><![CDATA[NFL
HONORS]]></name>

                                            <img>shows/halloffame.png</img>

                                            <seasons>

                                            <season
catId="253"><![CDATA[SEASON 2015]]></season>

                                            <season
catId="224"><![CDATA[SEASON 2014]]></season>

                                            </seasons>

                                            </show>

                                            <show>

                                            <name><![CDATA[NFL TOTAL
ACCESS]]></name>

                                            <img>shows/totalaccess.png</img>

                                            <seasons>

                                            <season
catId="254"><![CDATA[SEASON 2015]]></season>

                                            <season
catId="214"><![CDATA[SEASON 2014]]></season>

                                            <season
catId="181"><![CDATA[SEASON 2013]]></season>

                                            <season
catId="148"><![CDATA[SEASON 2012]]></season>

                                            <season
catId="115"><![CDATA[SEASON 2011]]></season>

                                            <season
catId="87"><![CDATA[SEASON 2010]]></season>

                                            </seasons>

                                            </show>

                                            <show>


<name><![CDATA[PLAYBOOK]]></name>

                                            <img>shows/playbook.png</img>

                                            <seasons>

                                            <season
catId="255"><![CDATA[SEASON 2015]]></season>

                                            <season
catId="213"><![CDATA[SEASON 2014]]></season>

                                            <season
catId="180"><![CDATA[SEASON 2013]]></season>

                                            <season
catId="147"><![CDATA[SEASON 2012]]></season>

                                            <season
catId="114"><![CDATA[SEASON 2011]]></season>

                                            <season
catId="86"><![CDATA[SEASON 2010]]></season>

                                            </seasons>

                                            </show>

                                            <show>

                                            <name><![CDATA[SOUND
FX]]></name>

                                            <img>shows/soundfx.png</img>

                                            <seasons>

                                            <season
catId="256"><![CDATA[SEASON 2015]]></season>

                                            <season
catId="215"><![CDATA[SEASON 2014]]></season>

                                            <season
catId="183"><![CDATA[SEASON 2013]]></season>

                                            <season
catId="150"><![CDATA[SEASON 2012]]></season>

                                            <season
catId="118"><![CDATA[SEASON 2011]]></season>

                                            </seasons>

                                            </show>

                                            <show>

                                            <name><![CDATA[SUPER BOWL
ARCHIVES]]></name>

                                            <img>shows/superbowl.png</img>

                                            <seasons>

                                            <season
catId="117"><![CDATA[ARCHIVES]]></season>

                                            </seasons>

                                            </show>

                                            <show>

                                            <name><![CDATA[TOP 100
PLAYERS]]></name>


<img>shows/top100players.png</img>

                                            <seasons>

                                            <season
catId="257"><![CDATA[SEASON 2015]]></season>

                                            <season
catId="217"><![CDATA[SEASON 2014]]></season>

                                            <season
catId="185"><![CDATA[SEASON 2013]]></season>

                                            <season
catId="153"><![CDATA[SEASON 2012]]></season>

                                            <season
catId="121"><![CDATA[SEASON 2011]]></season>

                                            </seasons>

                                            </show>

                                            </nflnShows>

                                            </result>
14:21:12 T:5000  NOTICE: [pigskin]: RedZone is not on air.
14:21:32 T:6736  NOTICE: Thread FileCache start, auto delete: false
14:21:37 T:5508  NOTICE: Previous line repeats 4 times.
14:21:37 T:5508   ERROR: CScriptInvocationManager::ExecuteAsync - Not
executing non-existing script
special://home/addons/plugin.program.tbs/connectivity.py
14:21:44 T:4672   ERROR: CCurlFile::FillBuffer - Failed: Timeout was
reached(28)
14:21:44 T:4672   ERROR: CCurlFile::Open failed with code 0 for
http://xty.me/xunitytalk/addons/addons.xml.md5
14:21:44 T:4672   ERROR: XFILE::CFileCache::Open - failed to open source <
http://xty.me/xunitytalk/addons/addons.xml.md5>
14:21:44 T:4672   ERROR: Failed to fetch checksum for directory listing
http://xty.me/xunitytalk/addons/addons.xml for repository
repository.xunitytalk.
14:21:44 T:6656  NOTICE: Thread FileCache start, auto delete: false
14:21:45 T:4672  NOTICE: Previous line repeats 2 times.
14:21:45 T:4672   ERROR: CCurlFile::Open failed with code 404 for
https://github.com/whufclee/kodistuff/raw/master/zips/addons.xml.md5
14:21:45 T:4672   ERROR: XFILE::CFileCache::Open - failed to open source <
https://github.com/whufclee/kodistuff/raw/master/zips/addons.xml.md5>
14:21:45 T:4672   ERROR: Failed to fetch checksum for directory listing
https://github.com/whufclee/kodistuff/raw/master/zips/addons.xml for
repository repository.whufclee.dev.
14:21:45 T:6844  NOTICE: Thread FileCache start, auto delete: false
14:22:04 T:7140  NOTICE: Previous line repeats 9 times.
14:22:04 T:7140   ERROR: XFILE::CDirectory::GetDirectory - Error getting
C:\Users\aomendoza\AppData\Roaming\Kodi\userdata\addon_data\plugin.video.genesis\TVShows\
14:22:07 T:5508   ERROR: CScriptInvocationManager::ExecuteAsync - Not
executing non-existing script
special://home/addons/plugin.program.tbs/connectivity.py

I hope this is what your looking for

Thanks

**Closed** 2015-09-28 05:23 UTC
Labels: invalid

**Comment by Alexqw** [comment] 2015-09-28 08:15
@sportshd So, it looks like you posted your log, and then decided to delete it... Not terribly helpful, but thankfully I still have the email.

Your log indicated that you have Game Pass Domestic, and are connecting from the US. Unlike Game Pass International, games (and RedZone includes games) are blacked out while they're being played.

So, this is not a bug, and is instead the service working as intended.

If you were able to play RedZone through the web player, please let me know and I can easily add support.

---Alex

For future reference, this is the rzPhase code he received:

    <rzPhase>none_in</rzPhase>
