### ISSUE TITLE
Game Pass no access

### ISSUE THREAD

**Issue by msmittag** [Alexqw/xbmc-gamepass#247] opened 2016-08-09 10:19 UTC
Dear Friends,

I run KODI on a Raspberry Pi3 with OpenElec operating system mainly to watch the NFL from Germany via the Game Pass Add-on.

I registered for a free test week and anything worked perfect. I was very pleased with the service so I signed up for the whole season. Sorrowly after the test week ended my access was cancelled and now that my full subscription is active I can't get it to work anymore. My credentials are correct as I am able to login and watch games on my desktop computer via the browser.

I already tried:

- resetting my RB Pi and reinstall anything from the start
- changed the internet access (tethering from my phone) to rule out router problems
- changed password several times

The thing is I get the 'bad jujumagumbo'-error whatever password I type into the configuration - correct one, wrong one, even no one. My guess is that the password is not submitted correctly or at all.

Anyone with a good idea or advice?

Cheers
Michael

**Comment by Alexqw** [comment] 2016-08-09 13:00
@msmittag Can you enable debugging both in Kodi and on the addon and provide a log? That'll help narrow down what the problem is; "bad jujumagumbo" is our catch-all error. Bad credentials should raise a login error, so likely something else is wrong.

---Alex

**Comment by msmittag** [comment] 2016-08-10 16:59
Hey Guys,

many thanks for trying to help me.

@Ghoschdi - I got Kodi 15.2 Git:02e7013 (Compiled: Mar 1 2016)
Never the less I am more than willing to take your advive and reinstall from ZIP. Just - although I'm working in IT consider me a Newbie when it comes to all this. How exactly does the installation work?

@Alexqw - I activated both debugging options. Where will I find the LOG-files you need (see above - the Newbie-thing...)

Greetings
Michael

**Comment by Ghoschdi** [comment] 2016-08-10 19:25
Any reason you are not running the latest stable 16.2? If not, try upgrading to 16.2 and use the latest version of NFL GP from the Repo. My issue is purely related to upgrading to the 17.x branch with an installed version of NFL GP from the repo, that does not support 17.x out of the box.

**Comment by bobbylocs** [comment] 2016-08-11 01:53
I can't login on any kodi devices firetvs and my phone and Nvidia Shield. All are on SPMC 16.4.0 of kodi. I've installed 16.1 on phone and app will not login. Login is the whole problem. Can someone plz help. I can login fine on the website just add-on the problem. I'm on the latest verison of gamepads add-on thanks.

**Comment by Alexqw** [comment] 2016-08-11 07:01
@bobbylocs You will need to provide a debug log for us to troubleshoot this. Both you and @msmittag can follow those directions [here](http://kodi.wiki/view/Log_file). In addition, go into the GamePass addon's setting and enable debugging.

@msmittag I agree with @Ghoschdi, you should be running latest stable (16.2). We havn't released for Kodi 15.x in awhile, so you're currently running a somewhat older version of this addon.

---Alex

**Comment by Ghoschdi** [comment] 2016-08-11 07:38
@bobbylocs : Sorry, i do not use the spinoff SPMC, but the regular Kodi so i can only guess. I agree with @Alexqw that w/o logs it will be difficult to nail that. But happy to support as soon as we have more details.

**Comment by bobbylocs** [comment] 2016-08-11 13:30
[kodilogs.zip](https://github.com/Alexqw/xbmc-gamepass/files/413303/kodilogs.zip)
Here are my logs from a fresh install of kodi 16.1 stable verison failed login.

**Comment by Ghoschdi** [comment] 2016-08-11 14:04
Just to make sure: You are an US resident as you use GP domestic?
The primary error should be this:
```
ERROR: /storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/script.module.requests/lib/requests/packages/urllib3/connection.py:266: SubjectAltNameWarning: Certificate for gamepass.nfl.com has no `subjectAltName`, falling back to check for a `commonName` for now. This feature is being removed by major browsers and deprecated by RFC 2818. (See https://github.com/shazow/urllib3/issues/497 for details.)
                                              SubjectAltNameWarning
06:21:30 T:18446744072929147184   DEBUG: [pigskin]: Response code: 200
06:21:30 T:18446744072929147184   DEBUG: [pigskin]: Response: <?xml version="1.0" encoding="UTF-8"?>
                                            <result>
                                            	
                                            		<code>loginfailed</code>
```
The result is GP does not provide a username back and you fail to login.

**Comment by bobbylocs** [comment] 2016-08-11 14:11
I am on the US but using a VPN outside country which for sideload NFL gamepass app works fine on all devices so logins just fine. If I login on add-on under domestic still gives me same login error

**Comment by Ghoschdi** [comment] 2016-08-11 14:17
@bobbylocs : Understood - your log just stated that it tried to login domestic and your location is US. So, if the VPN connection works for your Kodi install and GP is set to international, you have to wait for Alex, sorry.

**Comment by bobbylocs** [comment] 2016-08-11 14:38
I do have it set to international. So you mean to till me it its saying I'm in the US?

**Comment by Ghoschdi** [comment] 2016-08-11 14:59
This is what your log says, yes```
 <isGPDomestic>true</isGPDomestic>
                                            		<nflAccessToken></nflAccessToken>
                                            		<nflConcurrentId></nflConcurrentId>
                                            	
                                            	<country>US</country>
```

**Comment by msmittag** [comment] 2016-08-11 15:07
@Ghoschdi - I just tried to find some information on how to update to KODI 16.2 but it seems on the net is no description that I understand (again - Newbie to all this). Could you provide a link to a step-by-step installation guide?

**Comment by bobbylocs** [comment] 2016-08-11 15:08
I was fine able to login but only on domestic? With VPN on. So why with VPN on can I login the gamepass app international just fine but on add-on on Kodi will only login on domestic side?

**Comment by Ghoschdi** [comment] 2016-08-11 15:25
@msmittag: First of all sorry, but it mean 16.1. And there is a repo you can add to your PI. Details here: https://www.raspberrypi.org/forums/viewtopic.php?p=832735#p832735 - it upgrades Kodi fine from there

@bobbylocs: So, are you telling me that you are now able to login if you set the addon to domestic? But it does not work with international?

**Comment by bobbylocs** [comment] 2016-08-11 15:28
Correct

**Comment by bobbylocs** [comment] 2016-08-11 15:29
Just now I was able to login on Kodi 16.1

**Comment by Alexqw** [comment] 2016-08-11 19:28
@bobbylocs So, just to confirm: on Kodi 16.1 you can login, but not play anything?

---Alex

**Comment by bobbylocs** [comment] 2016-08-11 19:29
Well there nothing to play on domestic side right? And yes when I enter international it gives login error with VPN outside the country

**Comment by bobbylocs** [comment] 2016-08-11 19:51
Same VPN will play NFL gamepass app just fine on international

**Comment by bobbylocs** [comment] 2016-08-11 20:44
Ok sorry its working on Kodi 16.1 now international I was putting Canada and Mexico that was the issue. Has be Europe I picked England sorry thanks for the help

**Comment by msmittag** [comment] 2016-08-12 18:32
Hey Guys,

I just installed the latest Beta of OpenElec including Kodi 16.1 on my Pi an IT WORKS! Consider me a happy camper! Many thanks for your help and support. I hope your team will do you proud this season - as long as they don't beat the Niners. But what am I saying - anyone beats the Niners these days.

Again - many thanks
Michael

**Comment by kaileu** [comment] 2016-08-12 18:59
Glad to hear everything solved :)
Go Hawks!

Mit freundlichen Grüßen
Kai Leutner

**Comment by Alexqw** [comment] 2016-08-12 19:07
@msmittag Glad to hear everything is working. Closing. :-)

---Alex

Go Pack. :-D

**Closed by Alexqw** 2016-08-12 19:07 UTC
