### ISSUE TITLE
Not sure what's up

### ISSUE THREAD

**Issue by eth-0** [Alexqw/xbmc-gamepass#209] opened 2015-09-20 19:11 UTC
Keep getting the standard juju error whenever I try to stream any game.  I did a 'tail -f' of kodi.log and tried to open a stream.  The output logs are found here:
http://pastebin.com/MF33BRsk

I'm running Kodi Helix on OpenELEC on a Raspberry Pi 2.

**Comment by kaileu** [comment] 2015-09-20 19:42
It looks like you want to watch a blackouted game.

Mit freundlichen Grüßen
KaiLeu

**Comment by eth-0** [comment] 2015-09-20 20:39
What determines a black out? I thought all regular season games were available via GamePass?  I was trying to watch it live.  Here's the log when trying to watch the same game after the final:
http://pastebin.com/PGFcD1LD

**Comment by eth-0** [comment] 2015-09-20 20:58
I should also mention that this happens when I try to play any game at all.

**Comment by Alexqw** [comment] 2015-09-22 06:50
@eth-0 Game Pass comes in two flavors, Domestic and International. The Domestic service, due to the NFL's contracts with the networks, is blacked out entirely when games are being played. With International, this is not the case, except for a few countries (UK, Ireland, etc) blacking out specific games. NFL Game Pass's FAQ (in the support section of the Game Pass website) explains the blackouts for your region.

This is a duplicate of #207, so I'm going to close it.

Thanks for the bug report. -)

---Alex

**Closed by Alexqw** 2015-09-22 06:50 UTC
