### ISSUE TITLE
Unable to open games List

### ISSUE THREAD

**Issue by codebakery-ch** [Alexqw/xbmc-gamepass#236] opened 2016-07-20 19:31 UTC
hi there

I really enjoy your plugin! thanks for the work! :+1: 

Recently, I switched to an Android TV and put Kodi on it. Now as the new season starts, I get this error when trying to open the gamepass screen:

`21:16:41 T:18446744071877557136  NOTICE: [plugin.video.nfl.gamepass-0.9.0]: Traceback (most recent call last):   File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.nfl.gamepass/default.py", line 411, in onClick self.display_seasons_weeks()
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.nfl.gamepass/default.py", line 236, in display_seasons_weeks
                                                weeks = self.seasons_and_weeks[self.selected_season]
                                            KeyError: u'2016'`

maybe thats something new? I think it worked like a charm just a month ago or so when I tried it...

thanks :)

**Comment by kaileu** [comment] 2016-07-20 19:33
Yes the list returns from the nfl is empty. We didn't catch this case  
so the app is broken. If the value isn't empty anymore because the nfl  
return a valid list everything will work again :)

Mit freundlichen Grüßen
Kai

**Comment by codebakery-ch** [comment] 2016-07-20 19:46
danke mann! bin fast froh dass es die App ist und kein Android Seich :)

seriously, love the app! have been using it from day 1. keep it up :)

**Comment by Displayel** [comment] 2016-07-21 15:13
so what exactly does this mean is this fixable ?

**Comment by kaileu** [comment] 2016-07-21 15:16
Yes but i don't know if a dev has time for it.
Nevertheless as soon as the NFL return valid information it will work  
automatically.


Mit freundlichen Grüßen
Kai Leutner

**Comment by Displayel** [comment] 2016-07-21 15:19
Hi Kai
thanks for the heads up, can you elaborate a little further ?

did this issue happen before ?

**Comment by kaileu** [comment] 2016-07-21 15:24
If you open the gamepass app an any other device with a official app  
you see that the new calender is out. But there won't be display any  
game. The reason is that they changed the year but without data at the  
moment. So the nfl has to fill up the calender first and then the  
addon will work again.

The Problem is we parse an xml file and search for the game data. But  
there is no gamedata at the moment.
We didn't catch this parsing error so the error occours.

Mit freundlichen Grüßen
Kai

**Comment by Alexqw** [comment] 2016-07-21 15:25
@kaileu So the official app is unable to play games? If so, then I'm ok with keeping this closed. But if they are able to get game info and can play games, then we should figure out of there's a new URL they're using. They do that from time to time. :-/

---Alex

**Comment by kaileu** [comment] 2016-07-21 15:30
The official app can play older games. But the gamelist for 2016 is empty.

We open directly the new season and parse the information.
But we don't accept an empty Gamelist. So it runs in an parsing error.  
If we would still open the old season at beginning the error wouldn't  
occoure.

Mit freundlichen Grüßen
Kai Leutner

**Comment by Alexqw** [comment] 2016-07-21 15:37
@kaileu Ahh, ok. Yeah, we should handle that and log appropriately in the debug log. Reopening.

---Alex

**Comment by BaumSchorle** [comment] 2016-07-21 17:50
Just provided a quick fix for this, could someone please test this?

**Comment by kaileu** [comment] 2016-07-21 18:04
@BaumSchorle
Works for me

Mit freundlichen Grüßen
Kai Leutner

**Comment by Displayel** [comment] 2016-07-21 18:36
doesn´t work for me, i just changed the new file default.py and the "some bad....." error is still showing up, i deinstalled the app completely afterwards and now when i try to install again it says "fehler beim installieren des addons"

**Comment by Alexqw** [comment] 2016-07-21 18:40
@BaumSchorle Can't test right now, but the patch looks sane to me. Thanks for doing this real quick. :-)

@Displayel The latest patch BaumSchorle just wrote is not in the kodi repos yet. This is the development area, where we break/test/fix things before we ship to the main Kodi repo. You'll have to download the latest master and install it by hand.

---Alex

**Comment by Alexqw** [comment] 2016-07-21 18:43
@Displayel Just to provide a bit more info, you can go to the main page of the repo and click on "Download Zip" on the right side. Then install in Kodi using that.

---Alex

**Comment by Displayel** [comment] 2016-07-21 18:50
i tried it, the first time the addon installed but the old games still didnt play..-then i deinstalled and tried to install from zip file again, but now this error message in thr right lowe corner shows up "fehler beim installieren des zip files"

**Comment by kaileu** [comment] 2016-07-21 18:51
Restart Kodi.

Mit freundlichen Grüßen
Kai

**Comment by Displayel** [comment] 2016-07-21 18:57
what can i say...-that easy...works again...you guys are fantastic...thank you

**Comment by HenioH** [comment] 2016-07-21 19:22
Thanks for the quick fix! Much Appreciated!.. Will there be a new addon up for the new 2016 season once NFL places some content in that 2016 section?

**Comment by Alexqw** [comment] 2016-07-21 21:17
@HenioH The addon will be updated going into the 2016 season. Game Pass tends to make quite a few changes during the preseason that breaks stuff, and we get to play catch-up. So, assuming they don't do anything crazy/impossible, everything should by the time the regular season starts.

---Alex

**Closed by Alexqw** 2016-07-21 21:17 UTC
